// Shared type definitions for Electron IPC communication

// =============================================================================
// OCTOPUS PROTOCOL TYPES (Re-exported from main types)
// =============================================================================

/**
 * Event types for Event Stream (Desktop → Vibe Brain)
 * Requirements: 2.3
 */
export type EventType =
  | 'ACTIVITY_LOG'
  | 'STATE_CHANGE'
  | 'USER_ACTION'
  | 'HEARTBEAT'
  | 'DESKTOP_APP_USAGE'
  | 'DESKTOP_IDLE'
  | 'DESKTOP_WINDOW_CHANGE';

/**
 * Client types for identifying the source/target of events and commands
 */
export type ClientType = 'web' | 'desktop' | 'browser_ext' | 'mobile';

/**
 * Command types for Command Stream (Vibe Brain → Desktop)
 * Requirements: 2.4
 */
export type CommandType =
  | 'SYNC_STATE'
  | 'EXECUTE_ACTION'
  | 'UPDATE_POLICY'
  | 'SHOW_UI';

/**
 * Action types that can be executed by desktop client
 */
export type DesktopActionType =
  | 'CLOSE_APP'
  | 'HIDE_APP'
  | 'BRING_TO_FRONT'
  | 'SHOW_NOTIFICATION';

/**
 * Activity categories for productivity tracking
 */
export type ActivityCategory = 'productive' | 'neutral' | 'distracting';

/**
 * Connection quality levels
 */
export type ConnectionQuality = 'good' | 'degraded' | 'poor';

/**
 * Command priority levels
 */
export type CommandPriority = 'low' | 'normal' | 'high' | 'critical';

// =============================================================================
// BASE EVENT INTERFACE (Octopus Protocol)
// =============================================================================

/**
 * Base interface for all events from Desktop to Vibe Brain
 * Requirements: 2.1, 2.3
 */
export interface BaseEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: EventType;
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
}

/**
 * Activity log payload for desktop app usage
 * Requirements: 4.1, 4.4
 */
export interface DesktopActivityPayload {
  source: 'desktop_app';
  /** App bundle ID */
  identifier: string;
  /** App name */
  title: string;
  /** Duration in seconds */
  duration: number;
  category: ActivityCategory;
  metadata?: {
    appBundleId?: string;
    windowTitle?: string;
    isActive?: boolean;
  };
}

/**
 * Desktop app usage event
 * Requirements: 4.1, 4.4
 */
export interface DesktopAppUsageEvent extends BaseEvent {
  eventType: 'DESKTOP_APP_USAGE';
  payload: DesktopActivityPayload;
}

/**
 * Desktop idle event payload
 * Requirements: 4.2
 */
export interface DesktopIdlePayload {
  /** Idle duration in seconds */
  idleSeconds: number;
  /** Whether user is currently idle */
  isIdle: boolean;
  /** Last activity timestamp */
  lastActivityTime: number;
}

/**
 * Desktop idle detection event
 * Requirements: 4.2
 */
export interface DesktopIdleEvent extends BaseEvent {
  eventType: 'DESKTOP_IDLE';
  payload: DesktopIdlePayload;
}

/**
 * Desktop window change payload
 * Requirements: 4.3
 */
export interface DesktopWindowChangePayload {
  /** Previous active app bundle ID */
  fromAppBundleId: string;
  /** Previous active app name */
  fromAppName: string;
  /** New active app bundle ID */
  toAppBundleId: string;
  /** New active app name */
  toAppName: string;
  /** Time spent on previous app in seconds */
  timeOnPreviousApp: number;
}

/**
 * Desktop window/app change event
 * Requirements: 4.3
 */
export interface DesktopWindowChangeEvent extends BaseEvent {
  eventType: 'DESKTOP_WINDOW_CHANGE';
  payload: DesktopWindowChangePayload;
}

/**
 * Heartbeat payload for desktop client
 * Requirements: 7.5
 */
export interface DesktopHeartbeatPayload {
  clientVersion: string;
  platform: 'macos' | 'windows' | 'linux';
  connectionQuality: ConnectionQuality;
  /** Hash of local state for conflict detection */
  localStateHash: string;
  /** Desktop-specific capabilities */
  capabilities: string[];
  /** Seconds since client start */
  uptime: number;
  /** Current focus enforcer state */
  focusEnforcerState?: {
    isMonitoring: boolean;
    isWithinWorkHours: boolean;
    isPomodoroActive: boolean;
    idleSeconds: number;
  };
}

/**
 * Desktop heartbeat event
 */
export interface DesktopHeartbeatEvent extends BaseEvent {
  eventType: 'HEARTBEAT';
  payload: DesktopHeartbeatPayload;
}

/**
 * Union type for all desktop events
 */
export type DesktopEvent =
  | DesktopAppUsageEvent
  | DesktopIdleEvent
  | DesktopWindowChangeEvent
  | DesktopHeartbeatEvent;

// =============================================================================
// BASE COMMAND INTERFACE (Octopus Protocol)
// =============================================================================

/**
 * Base interface for all commands from Vibe Brain to Desktop
 * Requirements: 2.2, 2.4
 */
export interface BaseCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: CommandType;
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
}

/**
 * Execute action payload for desktop
 * Requirements: 8.3
 */
export interface DesktopExecuteActionPayload {
  action: DesktopActionType;
  parameters: Record<string, unknown>;
  /** Milliseconds */
  timeout?: number;
  fallbackAction?: DesktopActionType;
}

/**
 * Execute action command for desktop
 */
export interface DesktopExecuteActionCommand extends BaseCommand {
  commandType: 'EXECUTE_ACTION';
  payload: DesktopExecuteActionPayload;
}

/**
 * Sleep enforcement app for policy
 * Requirements: 11.1
 */
export interface PolicySleepEnforcementApp {
  bundleId: string;
  name: string;
}

/**
 * Sleep time configuration for policy
 * Requirements: 9.4, 11.1, 11.2
 */
export interface PolicySleepTime {
  /** Whether sleep time enforcement is enabled */
  enabled: boolean;
  /** Sleep start time in "HH:mm" format */
  startTime: string;
  /** Sleep end time in "HH:mm" format */
  endTime: string;
  /** Apps to close during sleep time */
  enforcementApps: PolicySleepEnforcementApp[];
  /** Whether currently within the sleep time window */
  isCurrentlyActive: boolean;
  /** Whether sleep enforcement is currently snoozed */
  isSnoozed: boolean;
  /** Unix timestamp when snooze ends (if snoozed) */
  snoozeEndTime?: number;
}

/**
 * Ad-hoc focus session for policy
 * Requirements: 2.3, 13.1, 13.2
 */
export interface PolicyAdhocFocusSession {
  active: boolean;
  endTime: number;
  /** Whether this session overrides sleep time enforcement */
  overridesSleepTime?: boolean;
}

/**
 * Over rest configuration for policy
 * Requirements: 15.2, 15.3, 16.1-16.5
 */
export interface PolicyOverRest {
  /** Whether user is currently in over rest state */
  isOverRest: boolean;
  /** Minutes over the normal rest duration */
  overRestMinutes: number;
  /** Apps to close during over rest */
  enforcementApps: PolicySleepEnforcementApp[];
  /** Whether to bring app to front */
  bringToFront: boolean;
}

/**
 * Policy for desktop client
 * Requirements: 10.5, 10.6
 */
export interface DesktopPolicy {
  version: number;
  enforcementMode: 'strict' | 'gentle';
  workTimeSlots: PolicyTimeSlot[];
  skipTokens: PolicySkipTokenConfig;
  distractionApps: PolicyDistractionApp[];
  updatedAt: number;
  /** Sleep time configuration (optional) */
  sleepTime?: PolicySleepTime;
  /** Ad-hoc focus session (optional) */
  adhocFocusSession?: PolicyAdhocFocusSession;
  /** Over rest configuration (optional) */
  overRest?: PolicyOverRest;
}

/**
 * Time slot for policy
 */
export interface PolicyTimeSlot {
  /** 0-6 (Sunday = 0) */
  dayOfWeek: number;
  startHour: number;
  startMinute: number;
  endHour: number;
  endMinute: number;
}

/**
 * Skip token config for policy
 */
export interface PolicySkipTokenConfig {
  remaining: number;
  maxPerDay: number;
  delayMinutes: number;
}

/**
 * Distraction app for policy
 */
export interface PolicyDistractionApp {
  bundleId: string;
  name: string;
  action: 'force_quit' | 'hide_window';
}

/**
 * Update policy payload
 */
export interface DesktopUpdatePolicyPayload {
  policyType: 'full' | 'partial';
  policy: DesktopPolicy;
  effectiveTime: number;
}

/**
 * Update policy command for desktop
 */
export interface DesktopUpdatePolicyCommand extends BaseCommand {
  commandType: 'UPDATE_POLICY';
  payload: DesktopUpdatePolicyPayload;
}

/**
 * Show UI payload
 */
export interface DesktopShowUIPayload {
  uiType: 'notification' | 'modal' | 'overlay' | 'toast';
  content: Record<string, unknown>;
  duration?: number;
  dismissible: boolean;
}

/**
 * Show UI command for desktop
 */
export interface DesktopShowUICommand extends BaseCommand {
  commandType: 'SHOW_UI';
  payload: DesktopShowUIPayload;
}

/**
 * Union type for all desktop commands
 */
export type DesktopCommand =
  | DesktopExecuteActionCommand
  | DesktopUpdatePolicyCommand
  | DesktopShowUICommand;

// =============================================================================
// CLIENT REGISTRATION TYPES
// =============================================================================

/**
 * Client registration request
 * Requirements: 9.1, 9.2
 */
export interface ClientRegistrationRequest {
  clientType: 'desktop';
  clientVersion: string;
  platform: 'macos' | 'windows' | 'linux';
  capabilities: string[];
  deviceName?: string;
}

/**
 * Client registration response
 */
export interface ClientRegistrationResponse {
  success: boolean;
  clientId?: string;
  error?: string;
}

/**
 * Command acknowledgment
 * Requirements: 2.6
 */
export interface CommandAcknowledgment {
  commandId: string;
  success: boolean;
  error?: string;
  timestamp: number;
}

// =============================================================================
// EXISTING TYPES (Electron Main Config, etc.)
// =============================================================================

export interface ElectronMainConfig {
  serverUrl: string;
  isDevelopment: boolean;
  autoLaunch: boolean;
}

// Work time slot configuration
export interface WorkTimeSlot {
  id: string;
  startTime: string; // HH:mm format
  endTime: string;   // HH:mm format
  enabled: boolean;
}

// Skip token configuration
export interface SkipTokenConfig {
  dailyLimit: number;
  maxDelayMinutes: number;
  usedToday: number;
  lastResetDate: string; // ISO date string
}

// Focus enforcer configuration
export interface FocusEnforcerConfig {
  workTimeSlots: WorkTimeSlot[];
  maxIdleMinutes: number;
  enforcementMode: 'strict' | 'gentle';
  repeatIntervalMinutes: number;
  distractionApps: DistractionApp[];
  skipTokens: SkipTokenConfig;
}

// Focus enforcer state
export interface FocusEnforcerState {
  isMonitoring: boolean;
  isWithinWorkHours: boolean;
  isPomodoroActive: boolean;
  idleSeconds: number;
  lastActivityTime: number;
  lastInterventionTime: number | null;
  interventionCount: number;
}

// Intervention action result
export interface InterventionAction {
  type: 'force_quit' | 'hide_window';
  apps: DistractionApp[];
}

export interface WindowState {
  isVisible: boolean;
  isFocused: boolean;
  bounds: { x: number; y: number; width: number; height: number };
}

export interface AppControlResult {
  success: boolean;
  error?: string;
}

export interface RunningApp {
  bundleId: string;
  name: string;
  pid: number;
  isActive: boolean;
}

export interface DistractionApp {
  bundleId: string;
  name: string;
  action: 'force_quit' | 'hide_window';
  isPreset: boolean;
}

export interface InterventionEvent {
  type: 'idle_alert' | 'distraction_detected';
  timestamp: number;
  idleSeconds?: number;
  distractionApp?: string;
}

export interface NotificationOptions {
  title: string;
  body: string;
  silent?: boolean;
  urgency?: 'normal' | 'critical' | 'low';
}

/**
 * Tray menu state for dynamic updates
 * Enhanced to support system state display and rest time tracking
 */
export interface TrayMenuState {
  // Existing fields
  pomodoroActive: boolean;
  pomodoroTimeRemaining?: string; // MM:SS format (e.g., "15:30")
  currentTask?: string;
  isWithinWorkHours: boolean; // Reserved for future use
  skipTokensRemaining: number;
  enforcementMode: 'strict' | 'gentle';
  /** Current app mode (development, staging, production) */
  appMode?: 'development' | 'staging' | 'production';
  /** Whether demo mode is active */
  isInDemoMode?: boolean;
  
  // New fields for enhanced functionality
  /** Current system state for non-pomodoro display */
  systemState: 'LOCKED' | 'PLANNING' | 'FOCUS' | 'REST' | 'OVER_REST';
  /** Rest countdown time in MM:SS format (pre-formatted) */
  restTimeRemaining?: string;
  /** Over-rest duration display (e.g., "15 min") (pre-formatted) */
  overRestDuration?: string;
  /** Daily pomodoro progress (e.g., "3/6") */
  dailyProgress?: string;
  /** Whether it's sleep time */
  isInSleepTime?: boolean;
}

// IPC Channel names
export const IPC_CHANNELS = {
  // Window control
  WINDOW_SHOW: 'window:show',
  WINDOW_HIDE: 'window:hide',
  WINDOW_BRING_TO_FRONT: 'window:bringToFront',
  WINDOW_TOGGLE: 'window:toggle',

  // Configuration
  CONFIG_GET: 'config:get',
  CONFIG_UPDATE: 'config:update',

  // Auto-launch
  AUTO_LAUNCH_ENABLE: 'autoLaunch:enable',
  AUTO_LAUNCH_DISABLE: 'autoLaunch:disable',
  AUTO_LAUNCH_IS_ENABLED: 'autoLaunch:isEnabled',

  // Tray
  TRAY_UPDATE_MENU: 'tray:updateMenu',
  TRAY_START_POMODORO: 'tray:start-pomodoro',
  TRAY_VIEW_STATUS: 'tray:view-status',
  TRAY_OPEN_SETTINGS: 'tray:open-settings',

  // App control
  APP_QUIT: 'app:quit',
  APP_HIDE: 'app:hide',
  APP_GET_RUNNING: 'app:getRunning',
  APP_CLOSE_DISTRACTION_APPS: 'app:closeDistractionApps',
  APP_IS_RUNNING: 'app:isRunning',

  // Permissions
  PERMISSION_CHECK_ACCESSIBILITY: 'permission:checkAccessibility',
  PERMISSION_REQUEST_ACCESSIBILITY: 'permission:requestAccessibility',

  // Focus enforcer
  FOCUS_INTERVENTION_TRIGGERED: 'focus:interventionTriggered',
  FOCUS_INTERVENTION_DISMISSED: 'focus:interventionDismissed',
  FOCUS_START_MONITORING: 'focus:startMonitoring',
  FOCUS_STOP_MONITORING: 'focus:stopMonitoring',
  FOCUS_GET_STATE: 'focus:getState',
  FOCUS_GET_CONFIG: 'focus:getConfig',
  FOCUS_UPDATE_CONFIG: 'focus:updateConfig',
  FOCUS_RECORD_ACTIVITY: 'focus:recordActivity',
  FOCUS_SET_POMODORO_ACTIVE: 'focus:setPomodoroActive',
  FOCUS_SKIP_INTERVENTION: 'focus:skipIntervention',
  FOCUS_DELAY_INTERVENTION: 'focus:delayIntervention',
  FOCUS_GET_REMAINING_TOKENS: 'focus:getRemainingSkipTokens',

  // Notifications
  NOTIFICATION_SHOW: 'notification:show',

  // Octopus Protocol - Client Registration (Requirements: 9.1, 9.2)
  OCTOPUS_REGISTER_CLIENT: 'octopus:registerClient',
  OCTOPUS_CLIENT_REGISTERED: 'octopus:clientRegistered',
  
  // Octopus Protocol - Event Stream (Requirements: 2.3)
  OCTOPUS_SEND_EVENT: 'octopus:sendEvent',
  OCTOPUS_EVENT_SENT: 'octopus:eventSent',
  
  // Octopus Protocol - Command Stream (Requirements: 2.4)
  OCTOPUS_COMMAND_RECEIVED: 'octopus:commandReceived',
  OCTOPUS_COMMAND_ACK: 'octopus:commandAck',
  
  // Octopus Protocol - Policy Updates (Requirements: 10.2, 10.3)
  OCTOPUS_POLICY_UPDATED: 'octopus:policyUpdated',
  
  // Octopus Protocol - State Sync (Requirements: 1.4, 1.7)
  OCTOPUS_STATE_SYNC: 'octopus:stateSync',

  // Sensor Reporter (Requirements: 4.1-4.5)
  SENSOR_START: 'sensor:start',
  SENSOR_STOP: 'sensor:stop',
  SENSOR_GET_STATE: 'sensor:getState',
  SENSOR_SET_USER_ID: 'sensor:setUserId',
  SENSOR_RECORD_ACTIVITY: 'sensor:recordActivity',

  // Heartbeat Manager (Requirements: 3.1, 1.4)
  HEARTBEAT_START: 'heartbeat:start',
  HEARTBEAT_STOP: 'heartbeat:stop',
  HEARTBEAT_GET_STATE: 'heartbeat:getState',
  HEARTBEAT_GET_LAST: 'heartbeat:getLastHeartbeat',
  HEARTBEAT_IS_CONNECTED: 'heartbeat:isConnected',
  HEARTBEAT_SET_USER_ID: 'heartbeat:setUserId',
  HEARTBEAT_SET_DEMO_MODE: 'heartbeat:setDemoMode',
  HEARTBEAT_SET_ACTIVE_POMODORO: 'heartbeat:setActivePomodoroId',
  HEARTBEAT_SEND: 'heartbeat:sendHeartbeat',
  HEARTBEAT_GET_CONFIG: 'heartbeat:getConfig',
  HEARTBEAT_EVENT: 'heartbeat:event',

  // Mode Detector (Requirements: 2.3, 2.5, 6.5, 10.1-10.8)
  MODE_GET_MODE: 'mode:getMode',
  MODE_GET_CURRENT_MODE: 'mode:getCurrentMode',
  MODE_IS_DEVELOPMENT: 'mode:isDevelopment',
  MODE_IS_PRODUCTION: 'mode:isProduction',
  MODE_IS_STAGING: 'mode:isStaging',
  MODE_IS_IN_DEMO_MODE: 'mode:isInDemoMode',
  MODE_SET_DEMO_MODE: 'mode:setDemoMode',
  MODE_GET_DISPLAY_INFO: 'mode:getDisplayInfo',
  MODE_SHOULD_ENFORCE: 'mode:shouldEnforce',
  MODE_CAN_QUIT_FREELY: 'mode:canQuitFreely',

  // Sleep Enforcer (Requirements: 11.1-11.5)
  SLEEP_GET_STATE: 'sleep:getState',
  SLEEP_GET_CONFIG: 'sleep:getConfig',
  SLEEP_REQUEST_SNOOZE: 'sleep:requestSnooze',
  SLEEP_CANCEL_SNOOZE: 'sleep:cancelSnooze',
  SLEEP_IS_IN_SLEEP_TIME: 'sleep:isInSleepTime',
  SLEEP_FORCE_ENFORCE: 'sleep:forceEnforce',
  SLEEP_STARTED: 'sleep:started',
  SLEEP_ENDED: 'sleep:ended',
  SLEEP_ENFORCED: 'sleep:enforced',
  SLEEP_SNOOZED: 'sleep:snoozed',
  SLEEP_SNOOZE_CANCELLED: 'sleep:snoozeCancelled',

  // Policy Cache (Requirements: 9.1, 9.2)
  POLICY_CACHE_GET_POLICY: 'policyCache:getPolicy',
  POLICY_CACHE_GET_CACHED_POLICY: 'policyCache:getCachedPolicy',
  POLICY_CACHE_GET_STATE: 'policyCache:getState',
  POLICY_CACHE_IS_STALE: 'policyCache:isStale',
  POLICY_CACHE_HAS_VALID_POLICY: 'policyCache:hasValidPolicy',
  POLICY_CACHE_IS_WITHIN_WORK_HOURS: 'policyCache:isWithinWorkHours',
  POLICY_CACHE_GET_ENFORCEMENT_MODE: 'policyCache:getEnforcementMode',
  POLICY_CACHE_GET_DISTRACTION_APPS: 'policyCache:getDistractionApps',
  POLICY_CACHE_GET_SKIP_TOKEN_CONFIG: 'policyCache:getSkipTokenConfig',

  // Auth Manager
  AUTH_GET_STATE: 'auth:getState',
  AUTH_LOGIN: 'auth:login',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_ON_CHANGE: 'auth:onChange',

  // Offline Event Queue (Requirements: 9.3, 9.6)
  OFFLINE_QUEUE_GET_STATE: 'offlineQueue:getState',
  OFFLINE_QUEUE_GET_QUEUE: 'offlineQueue:getQueue',
  OFFLINE_QUEUE_GET_PENDING: 'offlineQueue:getPendingEvents',
  OFFLINE_QUEUE_GET_FAILED: 'offlineQueue:getFailedEvents',
  OFFLINE_QUEUE_SYNC_ALL: 'offlineQueue:syncAll',
  OFFLINE_QUEUE_RETRY_FAILED: 'offlineQueue:retryFailed',
  OFFLINE_QUEUE_CLEAR: 'offlineQueue:clearQueue',
  OFFLINE_QUEUE_CLEAR_FAILED: 'offlineQueue:clearFailed',
  OFFLINE_QUEUE_SYNC_COMPLETE: 'offlineQueue:syncComplete',
} as const;

export type IpcChannelName = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
