// System state types matching the main VibeFlow application
export type SystemState = 'LOCKED' | 'PLANNING' | 'FOCUS' | 'REST' | 'OVER_REST';

// Enforcement mode types (Requirements 4.1)
export type EnforcementMode = 'strict' | 'gentle';

// =============================================================================
// OCTOPUS PROTOCOL TYPES (Requirements 2.3, 2.4, 5.18, 5.19)
// =============================================================================

/**
 * Event types for Event Stream (Browser Sentinel → Vibe Brain)
 */
export type OctopusEventType =
  | 'ACTIVITY_LOG'
  | 'STATE_CHANGE'
  | 'USER_ACTION'
  | 'HEARTBEAT'
  | 'TIMELINE_EVENT'
  | 'BLOCK_EVENT'
  | 'INTERRUPTION_EVENT'
  | 'BROWSER_ACTIVITY'
  | 'BROWSER_SESSION'
  | 'TAB_SWITCH'
  | 'BROWSER_FOCUS'
  | 'ENTERTAINMENT_MODE'
  | 'WORK_START';

/**
 * Client types for identifying the source/target
 */
export type ClientType = 'web' | 'desktop' | 'browser_ext' | 'mobile';

/**
 * Command types for Command Stream (Vibe Brain → Browser Sentinel)
 */
export type OctopusCommandType =
  | 'SYNC_STATE'
  | 'EXECUTE_ACTION'
  | 'UPDATE_POLICY'
  | 'SHOW_UI';

/**
 * Action types that can be executed by browser extension
 */
export type BrowserActionType =
  | 'CLOSE_TAB'
  | 'REDIRECT_TAB'
  | 'INJECT_OVERLAY'
  | 'ADD_SESSION_WHITELIST';

/**
 * Activity categories for productivity tracking
 */
export type ActivityCategory = 'productive' | 'neutral' | 'distracting';

/**
 * Navigation types for browser activity
 */
export type NavigationType = 'link' | 'typed' | 'reload' | 'back_forward' | 'other';

/**
 * Search engine types
 */
export type SearchEngine = 'google' | 'bing' | 'duckduckgo' | 'other';

/**
 * Browser focus states
 */
export type BrowserFocusState = 'focused' | 'blurred' | 'unknown';

/**
 * Interaction types for user engagement tracking
 */
export type InteractionType = 'click' | 'input' | 'scroll' | 'keypress' | 'video_play' | 'video_pause';

/**
 * Connection quality levels
 */
export type ConnectionQuality = 'good' | 'degraded' | 'poor';

/**
 * Command priority levels
 */
export type CommandPriority = 'low' | 'normal' | 'high' | 'critical';

// =============================================================================
// BASE EVENT INTERFACE (Requirements 2.3, 7.6)
// =============================================================================

/**
 * Base interface for all events from Browser Sentinel to Vibe Brain
 */
export interface OctopusBaseEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: OctopusEventType;
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
}

// =============================================================================
// BROWSER ACTIVITY EVENT (Requirements 5.18)
// =============================================================================

/**
 * Enhanced browser activity payload
 * Requirements: 5.6-5.20
 */
export interface BrowserActivityPayload {
  // Basic info
  url: string;
  title: string;
  domain: string;

  // Time tracking
  /** Unix timestamp (ms) */
  startTime: number;
  /** Unix timestamp (ms) */
  endTime: number;
  /** Total time on page (seconds) */
  duration: number;
  /** Time with user interaction (seconds) */
  activeDuration: number;
  /** Time without interaction (seconds) */
  idleTime: number;

  // Categorization
  category: ActivityCategory;
  /** 0-100 */
  productivityScore: number;

  // User engagement metrics
  /** 0-100 percentage */
  scrollDepth: number;
  /** clicks, inputs, etc. */
  interactionCount: number;

  // Media tracking
  isMediaPlaying: boolean;
  /** seconds */
  mediaPlayDuration: number;

  // Navigation context
  referrer?: string;
  navigationType: NavigationType;

  // Search tracking (for search engines)
  searchQuery?: string;
  searchEngine?: SearchEngine;
}

/**
 * Enhanced browser activity log with detailed tracking
 * Requirements: 5.6-5.20
 */
export interface BrowserActivityEvent extends OctopusBaseEvent {
  eventType: 'BROWSER_ACTIVITY';
  payload: BrowserActivityPayload;
}

// =============================================================================
// BROWSER SESSION EVENT (Requirements 5.19)
// =============================================================================

/**
 * Domain breakdown entry for browser sessions
 */
export interface DomainBreakdownEntry {
  domain: string;
  /** Duration in seconds */
  duration: number;
  /** Active duration in seconds */
  activeDuration: number;
  category: ActivityCategory;
  visitCount: number;
}

/**
 * Browser session payload
 * Requirements: 5.13-5.17
 */
export interface BrowserSessionPayload {
  sessionId: string;
  startTime: number;
  endTime: number;
  /** seconds */
  totalDuration: number;
  /** seconds with browser focused */
  activeDuration: number;

  // Domain breakdown
  domainBreakdown: DomainBreakdownEntry[];

  // Behavior patterns
  tabSwitchCount: number;
  /** switches within 3 seconds */
  rapidTabSwitches: number;
  uniqueDomainsVisited: number;

  // Productivity summary
  productiveTime: number;
  distractingTime: number;
  neutralTime: number;
  /** 0-100 */
  productivityScore: number;
}

/**
 * Browser session summary event
 * Requirements: 5.13-5.17
 */
export interface BrowserSessionEvent extends OctopusBaseEvent {
  eventType: 'BROWSER_SESSION';
  payload: BrowserSessionPayload;
}

// =============================================================================
// TAB SWITCH EVENT (Requirements 5.3, 5.17)
// =============================================================================

/**
 * Tab switch payload
 */
export interface TabSwitchPayload {
  fromTabId: number;
  toTabId: number;
  fromUrl: string;
  toUrl: string;
  fromDomain: string;
  toDomain: string;
  /** milliseconds */
  timeSinceLastSwitch: number;
  /** < 3 seconds since last switch */
  isRapidSwitch: boolean;
}

/**
 * Tab switch event for distraction detection
 * Requirements: 5.3, 5.17
 */
export interface TabSwitchEvent extends OctopusBaseEvent {
  eventType: 'TAB_SWITCH';
  payload: TabSwitchPayload;
}

// =============================================================================
// BROWSER FOCUS EVENT (Requirements 5.9, 5.16)
// =============================================================================

/**
 * Browser focus payload
 */
export interface BrowserFocusPayload {
  /** true = browser gained focus, false = lost focus */
  isFocused: boolean;
  previousState: BrowserFocusState;
  /** seconds (only when losing focus) */
  focusDuration?: number;
}

/**
 * Browser focus event
 * Requirements: 5.9, 5.16
 */
export interface BrowserFocusEvent extends OctopusBaseEvent {
  eventType: 'BROWSER_FOCUS';
  payload: BrowserFocusPayload;
}

// =============================================================================
// HEARTBEAT EVENT
// =============================================================================

/**
 * Heartbeat payload
 */
export interface HeartbeatPayload {
  clientVersion: string;
  platform: string;
  connectionQuality: ConnectionQuality;
  localStateHash: string;
  capabilities: string[];
  uptime: number;
}

/**
 * Periodic heartbeat from browser extension
 */
export interface HeartbeatEvent extends OctopusBaseEvent {
  eventType: 'HEARTBEAT';
  payload: HeartbeatPayload;
}

// =============================================================================
// ENTERTAINMENT MODE EVENT (Requirements 8.6, 10.3)
// =============================================================================

/**
 * Entertainment mode stop reason
 */
export type EntertainmentStopReason = 'manual' | 'quota_exhausted' | 'work_time_start';

/**
 * Entertainment mode event payload
 */
export interface EntertainmentModePayload {
  action: 'start' | 'stop';
  sessionId: string;
  timestamp: number;
  quotaUsedBefore: number;   // minutes
  quotaUsedAfter?: number;   // minutes (only for stop)
  duration?: number;         // seconds (only for stop)
  sitesVisited?: string[];   // domains visited during session
  reason?: EntertainmentStopReason;
}

/**
 * Entertainment mode event
 * Requirements: 8.6, 10.3
 */
export interface EntertainmentModeEvent extends OctopusBaseEvent {
  eventType: 'ENTERTAINMENT_MODE';
  payload: EntertainmentModePayload;
}

// =============================================================================
// WORK START EVENT (Requirements 14.1, 14.2, 14.9, 14.10)
// =============================================================================

/**
 * Work start event payload
 * Requirements: 14.1, 14.2, 14.9, 14.10
 */
export interface WorkStartPayload {
  date: string;                  // YYYY-MM-DD
  configuredStartTime: string;   // HH:mm
  actualStartTime: number;       // Unix timestamp
  delayMinutes: number;          // 0 if on-time or early, positive if late
  trigger: 'airlock_complete';   // What triggered the work start
}

/**
 * Work start event
 * Requirements: 14.1, 14.2, 14.9, 14.10
 */
export interface WorkStartEvent extends OctopusBaseEvent {
  eventType: 'WORK_START';
  payload: WorkStartPayload;
}

// =============================================================================
// UNION TYPE FOR ALL OCTOPUS EVENTS
// =============================================================================

/**
 * Union type for all browser sentinel events
 */
export type OctopusEvent =
  | BrowserActivityEvent
  | BrowserSessionEvent
  | TabSwitchEvent
  | BrowserFocusEvent
  | HeartbeatEvent
  | EntertainmentModeEvent
  | WorkStartEvent;

// =============================================================================
// COMMAND STREAM TYPES (Vibe Brain → Browser Sentinel)
// =============================================================================

/**
 * Base interface for all commands from Vibe Brain to Browser Sentinel
 * Requirements: 2.4, 8.6
 */
export interface OctopusBaseCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: OctopusCommandType;
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
}

/**
 * Sync state command payload
 */
export interface SyncStatePayload {
  syncType: 'full' | 'delta';
  version: number;
  state?: unknown;
  delta?: unknown;
}

/**
 * Sync state command
 */
export interface SyncStateCommand extends OctopusBaseCommand {
  commandType: 'SYNC_STATE';
  payload: SyncStatePayload;
}

/**
 * Execute action command payload
 */
export interface ExecuteActionPayload {
  action: BrowserActionType;
  parameters: Record<string, unknown>;
  timeout?: number;
  fallbackAction?: BrowserActionType;
}

/**
 * Execute action command
 */
export interface ExecuteActionCommand extends OctopusBaseCommand {
  commandType: 'EXECUTE_ACTION';
  payload: ExecuteActionPayload;
}

/**
 * Time slot for work time configuration
 */
export interface OctopusTimeSlot {
  dayOfWeek: number;
  startHour: number;
  startMinute: number;
  endHour: number;
  endMinute: number;
}

/**
 * Skip token configuration
 */
export interface SkipTokenConfig {
  remaining: number;
  maxPerDay: number;
  delayMinutes: number;
}

/**
 * Distraction app configuration
 */
export interface DistractionApp {
  bundleId: string;
  name: string;
  action: 'force_quit' | 'hide_window';
}

/**
 * Policy object distributed to clients
 * Requirements: 10.5, 10.6
 */
export interface OctopusPolicy {
  version: number;
  blacklist: string[];
  whitelist: string[];
  enforcementMode: EnforcementMode;
  workTimeSlots: OctopusTimeSlot[];
  skipTokens: SkipTokenConfig;
  distractionApps: DistractionApp[];
  updatedAt: number;
}

/**
 * Update policy command payload
 */
export interface UpdatePolicyPayload {
  policyType: 'full' | 'partial';
  policy: OctopusPolicy;
  effectiveTime: number;
}

/**
 * Update policy command
 */
export interface UpdatePolicyCommand extends OctopusBaseCommand {
  commandType: 'UPDATE_POLICY';
  payload: UpdatePolicyPayload;
}

/**
 * UI types for show UI command
 */
export type UIType = 'notification' | 'modal' | 'overlay' | 'toast';

/**
 * Show UI command payload
 */
export interface ShowUIPayload {
  uiType: UIType;
  content: Record<string, unknown>;
  duration?: number;
  dismissible: boolean;
}

/**
 * Show UI command
 */
export interface ShowUICommand extends OctopusBaseCommand {
  commandType: 'SHOW_UI';
  payload: ShowUIPayload;
}

/**
 * Union type for all commands
 */
export type OctopusCommand =
  | SyncStateCommand
  | ExecuteActionCommand
  | UpdatePolicyCommand
  | ShowUICommand;

// Work time slot for checking work hours
export interface WorkTimeSlot {
  id: string;
  startTime: string; // HH:mm format
  endTime: string;   // HH:mm format
  enabled: boolean;
}

// Entertainment blacklist entry
export interface EntertainmentBlacklistEntry {
  domain: string;
  isPreset: boolean;
  enabled: boolean;
  addedAt: number;
}

// Entertainment whitelist entry
export interface EntertainmentWhitelistEntry {
  pattern: string;
  description?: string;
  isPreset: boolean;
  enabled: boolean;
  addedAt: number;
}

// Policy cache stored locally in the extension
export interface PolicyCache {
  globalState: SystemState;
  blacklist: string[];
  whitelist: string[];
  sessionWhitelist: string[];
  lastSync: number;
  // Enhanced fields for focus enforcement (Requirements 4.1, 6.1)
  enforcementMode: EnforcementMode;
  workTimeSlots: WorkTimeSlot[];
  skipTokensRemaining: number;
  skipTokenDailyLimit: number;
  skipTokenMaxDelay: number;
  browserRedirectReplace: boolean;
  isAuthenticated: boolean;
  dashboardUrl: string;
  // Entertainment fields (Requirements 2.1, 2.3, 2.5, 2.6, 2.7)
  entertainmentBlacklist: EntertainmentBlacklistEntry[];
  entertainmentWhitelist: EntertainmentWhitelistEntry[];
  entertainmentQuotaMinutes: number;
  entertainmentCooldownMinutes: number;
  entertainmentModeActive: boolean;
}

// Activity log entry for tracking browser usage
export interface ActivityLog {
  url: string;
  title: string;
  startTime: number;
  duration: number;
  category: 'productive' | 'neutral' | 'distracting';
}

// Timeline event types (Requirements: 7.1, 7.2)
export type TimelineEventType = 
  | 'pomodoro'
  | 'distraction'
  | 'break'
  | 'scheduled_task'
  | 'activity_log'
  | 'block'
  | 'state_change'
  | 'interruption'
  | 'idle';

// Timeline event entry for detailed activity tracking
export interface TimelineEvent {
  type: TimelineEventType;
  startTime: number; // timestamp
  endTime?: number; // timestamp
  duration: number; // seconds
  title: string;
  metadata?: Record<string, unknown>;
}

// Block event for tracking blocked site access (Requirements: 7.4)
export interface BlockEvent {
  url: string;
  timestamp: number;
  blockType: 'hard_block' | 'soft_block' | 'entertainment_block';
  userAction?: 'proceeded' | 'returned';
  pomodoroId?: string;
}

// Interruption event for tracking focus interruptions (Requirements: 7.4)
export interface InterruptionEvent {
  timestamp: number;
  duration: number; // seconds
  source: 'blocked_site' | 'tab_switch' | 'idle' | 'manual';
  pomodoroId: string;
  details?: {
    url?: string;
    idleSeconds?: number;
  };
}

// Server messages (Server -> Extension)
export type ServerMessage =
  | { type: 'SYNC_POLICY'; payload: PolicyCache }
  | { type: 'STATE_CHANGE'; payload: { state: SystemState } }
  | { type: 'EXECUTE'; payload: ExecuteCommand };

export type ExecuteCommand =
  | { action: 'INJECT_TOAST'; params: { msg: string; type: 'info' | 'warning' } }
  | { action: 'SHOW_OVERLAY'; params: { type: 'soft_block' | 'screensaver' } }
  | { action: 'REDIRECT'; params: { url: string } }
  | { action: 'POMODORO_COMPLETE'; params: { pomodoroId: string; taskTitle: string } }
  | { action: 'IDLE_ALERT'; params: { idleSeconds: number; threshold: number } };

// Client messages (Extension -> Server)
export type ClientMessage =
  | { type: 'ACTIVITY_LOG'; payload: ActivityLog[] }
  | { type: 'URL_CHECK'; payload: { url: string } }
  | { type: 'USER_RESPONSE'; payload: { questionId: string; response: boolean } }
  | { type: 'TIMELINE_EVENT'; payload: TimelineEvent }
  | { type: 'TIMELINE_EVENTS_BATCH'; payload: TimelineEvent[] }
  | { type: 'BLOCK_EVENT'; payload: BlockEvent }
  | { type: 'INTERRUPTION_EVENT'; payload: InterruptionEvent };

// Extension storage structure
export interface ExtensionStorage {
  serverUrl: string;
  isConnected: boolean;
  policyCache: PolicyCache;
  pendingActivityLogs: ActivityLog[];
  pendingTimelineEvents: TimelineEvent[];
  currentPomodoroId?: string;
}

// Connection status for the popup
export interface ConnectionStatus {
  connected: boolean;
  serverUrl: string;
  systemState: SystemState;
  pomodoroCount: number;
  dailyCap: number;
  currentTaskTitle: string | null;
  currentPomodoroId: string | null;
}

// URL check result
export type UrlCheckResult = 'allow' | 'block' | 'soft_block';

// Enhanced URL check result with mode information (Requirements 4.3, 6.1)
export interface EnhancedUrlCheckResult {
  action: UrlCheckResult;
  enforcementMode: EnforcementMode;
  isWithinWorkHours: boolean;
  isPomodoroActive: boolean;
  skipTokensRemaining: number;
  blockedUrl?: string;
}
