import { z } from 'zod';
import prisma from '@/lib/prisma';
import type { Task, Priority } from '@prisma/client';
import { taskService } from './task.service';

// ============================================================================
// Types and Interfaces
// ============================================================================

export type ServiceResult<T> =
  | { success: true; data: T }
  | { success: false; error: { code: string; message: string; details?: Record<string, string[]> } };

/**
 * Subtask suggestion generated by the decomposer
 * Requirements: 2.2, 2.3
 */
export interface SubtaskSuggestion {
  title: string;
  estimatedMinutes: number;
  priority: Priority;
  rationale: string;
}

/**
 * Result of task decomposition analysis
 * Requirements: 2.1, 2.2
 */
export interface DecompositionResult {
  shouldOffer: boolean;              // Whether to offer decomposition
  suggestions: SubtaskSuggestion[];  // 2-5 subtask suggestions
  confidence: number;                // Confidence score 0-1
  taskType: string;                  // Detected task type
}

// ============================================================================
// Validation Schemas
// ============================================================================

export const SubtaskSuggestionSchema = z.object({
  title: z.string().min(1).max(500),
  estimatedMinutes: z.number().int().min(5).max(480),
  priority: z.enum(['P1', 'P2', 'P3']),
  rationale: z.string().min(1).max(500),
});

export const AcceptSuggestionsSchema = z.object({
  parentTaskId: z.string().uuid(),
  suggestions: z.array(SubtaskSuggestionSchema).min(1).max(5),
});

export const RecordFeedbackSchema = z.object({
  taskId: z.string().uuid(),
  suggestions: z.array(SubtaskSuggestionSchema),
  accepted: z.array(z.string()),
  rejected: z.array(z.string()),
});

export type AcceptSuggestionsInput = z.infer<typeof AcceptSuggestionsSchema>;
export type RecordFeedbackInput = z.infer<typeof RecordFeedbackSchema>;

// ============================================================================
// Constants and Patterns
// ============================================================================

/**
 * Task type patterns for keyword-based recognition
 * Requirements: 2.2
 */
interface DecompositionPattern {
  pattern: RegExp;
  taskType: string;
  suggestCount: number;
  subtaskTemplates: Array<{
    titleTemplate: string;
    priority: Priority;
    estimatedMinutes: number;
    rationale: string;
  }>;
}

const DECOMPOSITION_PATTERNS: DecompositionPattern[] = [
  {
    pattern: /implement|create|build|develop|add/i,
    taskType: 'implementation',
    suggestCount: 3,
    subtaskTemplates: [
      { titleTemplate: 'Design and plan {feature}', priority: 'P1', estimatedMinutes: 30, rationale: 'Planning before implementation reduces rework' },
      { titleTemplate: 'Implement core logic for {feature}', priority: 'P1', estimatedMinutes: 60, rationale: 'Core implementation is the main work' },
      { titleTemplate: 'Write tests for {feature}', priority: 'P2', estimatedMinutes: 30, rationale: 'Tests ensure correctness' },
    ],
  },
  {
    pattern: /refactor|migrate|upgrade|modernize/i,
    taskType: 'refactoring',
    suggestCount: 4,
    subtaskTemplates: [
      { titleTemplate: 'Analyze current {component} structure', priority: 'P1', estimatedMinutes: 25, rationale: 'Understanding current state is essential' },
      { titleTemplate: 'Plan refactoring approach for {component}', priority: 'P1', estimatedMinutes: 20, rationale: 'A clear plan prevents mistakes' },
      { titleTemplate: 'Execute refactoring of {component}', priority: 'P1', estimatedMinutes: 60, rationale: 'Main refactoring work' },
      { titleTemplate: 'Verify and test {component} changes', priority: 'P2', estimatedMinutes: 30, rationale: 'Ensure nothing is broken' },
    ],
  },
  {
    pattern: /test|debug|fix|resolve|troubleshoot/i,
    taskType: 'debugging',
    suggestCount: 2,
    subtaskTemplates: [
      { titleTemplate: 'Investigate and reproduce {issue}', priority: 'P1', estimatedMinutes: 30, rationale: 'Understanding the issue is half the solution' },
      { titleTemplate: 'Fix and verify {issue}', priority: 'P1', estimatedMinutes: 45, rationale: 'Apply fix and confirm resolution' },
    ],
  },
  {
    pattern: /design|plan|research|analyze|investigate/i,
    taskType: 'research',
    suggestCount: 3,
    subtaskTemplates: [
      { titleTemplate: 'Gather requirements for {topic}', priority: 'P1', estimatedMinutes: 30, rationale: 'Clear requirements guide research' },
      { titleTemplate: 'Research options for {topic}', priority: 'P1', estimatedMinutes: 45, rationale: 'Explore available solutions' },
      { titleTemplate: 'Document findings for {topic}', priority: 'P2', estimatedMinutes: 25, rationale: 'Documentation preserves knowledge' },
    ],
  },
  {
    pattern: /review|audit|check|validate|verify/i,
    taskType: 'review',
    suggestCount: 2,
    subtaskTemplates: [
      { titleTemplate: 'Review {subject} against criteria', priority: 'P1', estimatedMinutes: 40, rationale: 'Systematic review ensures thoroughness' },
      { titleTemplate: 'Document review findings for {subject}', priority: 'P2', estimatedMinutes: 20, rationale: 'Record findings for follow-up' },
    ],
  },
  {
    pattern: /integrate|connect|setup|configure/i,
    taskType: 'integration',
    suggestCount: 3,
    subtaskTemplates: [
      { titleTemplate: 'Prepare environment for {integration}', priority: 'P1', estimatedMinutes: 25, rationale: 'Proper setup prevents issues' },
      { titleTemplate: 'Implement {integration} connection', priority: 'P1', estimatedMinutes: 50, rationale: 'Core integration work' },
      { titleTemplate: 'Test {integration} end-to-end', priority: 'P2', estimatedMinutes: 30, rationale: 'Verify integration works correctly' },
    ],
  },
];

// Default pattern for unrecognized task types
const DEFAULT_PATTERN: DecompositionPattern = {
  pattern: /.*/,
  taskType: 'general',
  suggestCount: 3,
  subtaskTemplates: [
    { titleTemplate: 'Plan approach for {task}', priority: 'P1', estimatedMinutes: 20, rationale: 'Planning improves execution' },
    { titleTemplate: 'Execute main work for {task}', priority: 'P1', estimatedMinutes: 60, rationale: 'Core task execution' },
    { titleTemplate: 'Review and finalize {task}', priority: 'P2', estimatedMinutes: 20, rationale: 'Quality check before completion' },
  ],
};

// Minimum description length to trigger decomposition (Requirement 2.1)
const MIN_DESCRIPTION_LENGTH = 100;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Extract a short feature/topic name from task description
 */
function extractFeatureName(description: string): string {
  // Try to extract a meaningful short name from the description
  const words = description.split(/\s+/).slice(0, 5);
  const shortName = words.join(' ');
  return shortName.length > 50 ? shortName.substring(0, 47) + '...' : shortName;
}

/**
 * Detect task type based on keywords in description
 * Requirements: 2.2
 */
function detectTaskType(description: string): DecompositionPattern {
  for (const pattern of DECOMPOSITION_PATTERNS) {
    if (pattern.pattern.test(description)) {
      return pattern;
    }
  }
  return DEFAULT_PATTERN;
}

/**
 * Generate subtask suggestions based on detected pattern
 * Requirements: 2.2
 */
function generateSuggestionsFromPattern(
  description: string,
  pattern: DecompositionPattern,
  historicalEstimates: Map<string, number>
): SubtaskSuggestion[] {
  const featureName = extractFeatureName(description);
  
  return pattern.subtaskTemplates.slice(0, pattern.suggestCount).map(template => {
    // Replace placeholder with feature name
    const title = template.titleTemplate.replace('{feature}', featureName)
      .replace('{component}', featureName)
      .replace('{issue}', featureName)
      .replace('{topic}', featureName)
      .replace('{subject}', featureName)
      .replace('{integration}', featureName)
      .replace('{task}', featureName);
    
    // Use historical estimate if available, otherwise use template default
    const estimatedMinutes = historicalEstimates.get(pattern.taskType) ?? template.estimatedMinutes;
    
    return {
      title,
      estimatedMinutes,
      priority: template.priority,
      rationale: template.rationale,
    };
  });
}

/**
 * Calculate confidence score based on pattern match quality
 */
function calculateConfidence(description: string, pattern: DecompositionPattern): number {
  let confidence = 0.5; // Base confidence
  
  // Increase confidence if description is longer (more context)
  if (description.length > 200) confidence += 0.1;
  if (description.length > 300) confidence += 0.1;
  
  // Increase confidence for specific patterns (not default)
  if (pattern.taskType !== 'general') confidence += 0.2;
  
  // Cap at 0.95
  return Math.min(confidence, 0.95);
}

// ============================================================================
// Service Implementation
// ============================================================================

export const taskDecomposerService = {
  /**
   * Check if task description warrants decomposition offer
   * Requirement 2.1: When description > 100 characters, offer decomposition
   */
  shouldOfferDecomposition(taskDescription: string): boolean {
    if (!taskDescription) return false;
    return taskDescription.length > MIN_DESCRIPTION_LENGTH;
  },

  /**
   * Generate subtask suggestions for a task
   * Requirements: 2.2, 2.3
   * Returns 2-5 actionable subtasks with time estimates
   */
  async generateSubtaskSuggestions(
    userId: string,
    taskId: string,
    taskDescription: string
  ): Promise<ServiceResult<DecompositionResult>> {
    try {
      // Check if decomposition should be offered
      const shouldOffer = this.shouldOfferDecomposition(taskDescription);
      
      if (!shouldOffer) {
        return {
          success: true,
          data: {
            shouldOffer: false,
            suggestions: [],
            confidence: 0,
            taskType: 'none',
          },
        };
      }

      // Verify task exists and belongs to user
      const task = await prisma.task.findFirst({
        where: { id: taskId, userId },
      });

      if (!task) {
        return {
          success: false,
          error: {
            code: 'NOT_FOUND',
            message: 'Task not found',
          },
        };
      }

      // Detect task type based on keywords
      const pattern = detectTaskType(taskDescription);

      // Get historical time estimates for this user and task type
      const historicalEstimates = await this.getHistoricalEstimates(userId, pattern.taskType);

      // Generate suggestions
      const suggestions = generateSuggestionsFromPattern(
        taskDescription,
        pattern,
        historicalEstimates
      );

      // Calculate confidence
      const confidence = calculateConfidence(taskDescription, pattern);

      return {
        success: true,
        data: {
          shouldOffer: true,
          suggestions,
          confidence,
          taskType: pattern.taskType,
        },
      };
    } catch (error) {
      return {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: error instanceof Error ? error.message : 'Failed to generate suggestions',
        },
      };
    }
  },

  /**
   * Get historical time estimates based on user's past tasks
   * Requirements: 2.3
   * 
   * This method analyzes completed tasks to provide better time estimates:
   * 1. Filters tasks by type pattern (implementation, refactoring, etc.)
   * 2. Calculates actual time spent from completed pomodoros
   * 3. Uses median for robust estimation (less affected by outliers)
   * 4. Falls back to overall average if no type-specific data
   */
  async getHistoricalEstimates(
    userId: string,
    taskType: string
  ): Promise<Map<string, number>> {
    const estimates = new Map<string, number>();

    try {
      // Get completed tasks with actual time spent
      const completedTasks = await prisma.task.findMany({
        where: {
          userId,
          status: 'DONE',
        },
        include: {
          pomodoros: {
            where: { status: 'COMPLETED' },
          },
        },
        take: 100, // Last 100 completed tasks for better statistics
        orderBy: { updatedAt: 'desc' },
      });

      if (completedTasks.length === 0) {
        return estimates;
      }

      // Find the pattern for this task type
      const pattern = DECOMPOSITION_PATTERNS.find(p => p.taskType === taskType);
      
      // Filter tasks that match the task type pattern
      const matchingTasks = pattern
        ? completedTasks.filter(task => pattern.pattern.test(task.title))
        : completedTasks;

      // Calculate durations for matching tasks
      const typeDurations: number[] = [];
      for (const task of matchingTasks) {
        const actualMinutes = task.pomodoros.reduce((sum, p) => sum + p.duration, 0);
        if (actualMinutes > 0) {
          typeDurations.push(actualMinutes);
        }
      }

      // Calculate overall durations as fallback
      const allDurations: number[] = [];
      for (const task of completedTasks) {
        const actualMinutes = task.pomodoros.reduce((sum, p) => sum + p.duration, 0);
        if (actualMinutes > 0) {
          allDurations.push(actualMinutes);
        }
      }

      // Use type-specific median if we have enough data (at least 3 samples)
      if (typeDurations.length >= 3) {
        typeDurations.sort((a, b) => a - b);
        const median = typeDurations[Math.floor(typeDurations.length / 2)];
        estimates.set(taskType, median);
      } else if (allDurations.length > 0) {
        // Fall back to overall median
        allDurations.sort((a, b) => a - b);
        const median = allDurations[Math.floor(allDurations.length / 2)];
        estimates.set(taskType, median);
      }

      // Also calculate estimates for subtask types based on parent-child relationships
      const subtaskDurations = await this.getSubtaskDurations(userId);
      if (subtaskDurations.size > 0) {
        subtaskDurations.forEach((value, key) => {
          estimates.set(`subtask_${key}`, value);
        });
      }
    } catch {
      // Return empty estimates on error
    }

    return estimates;
  },

  /**
   * Get average durations for subtasks based on historical data
   * Requirements: 2.3
   */
  async getSubtaskDurations(userId: string): Promise<Map<string, number>> {
    const durations = new Map<string, number>();

    try {
      // Get completed subtasks (tasks with parentId)
      const subtasks = await prisma.task.findMany({
        where: {
          userId,
          status: 'DONE',
          parentId: { not: null },
        },
        include: {
          pomodoros: {
            where: { status: 'COMPLETED' },
          },
        },
        take: 50,
        orderBy: { updatedAt: 'desc' },
      });

      if (subtasks.length === 0) {
        return durations;
      }

      // Group by priority and calculate median
      const byPriority: Record<string, number[]> = { P1: [], P2: [], P3: [] };
      
      for (const task of subtasks) {
        const actualMinutes = task.pomodoros.reduce((sum, p) => sum + p.duration, 0);
        if (actualMinutes > 0) {
          byPriority[task.priority].push(actualMinutes);
        }
      }

      for (const [priority, times] of Object.entries(byPriority)) {
        if (times.length >= 2) {
          times.sort((a, b) => a - b);
          const median = times[Math.floor(times.length / 2)];
          durations.set(priority, median);
        }
      }
    } catch {
      // Return empty on error
    }

    return durations;
  },

  /**
   * Estimate time for a specific subtask based on historical data
   * Requirements: 2.3
   */
  async estimateSubtaskTime(
    userId: string,
    subtaskTitle: string,
    priority: Priority,
    defaultMinutes: number
  ): Promise<number> {
    try {
      // Try to find similar completed subtasks
      const similarTasks = await prisma.task.findMany({
        where: {
          userId,
          status: 'DONE',
          parentId: { not: null },
          priority,
        },
        include: {
          pomodoros: {
            where: { status: 'COMPLETED' },
          },
        },
        take: 20,
        orderBy: { updatedAt: 'desc' },
      });

      if (similarTasks.length === 0) {
        return defaultMinutes;
      }

      // Calculate actual durations
      const durations: number[] = [];
      for (const task of similarTasks) {
        const actualMinutes = task.pomodoros.reduce((sum, p) => sum + p.duration, 0);
        if (actualMinutes > 0) {
          durations.push(actualMinutes);
        }
      }

      if (durations.length === 0) {
        return defaultMinutes;
      }

      // Return median
      durations.sort((a, b) => a - b);
      return durations[Math.floor(durations.length / 2)];
    } catch {
      return defaultMinutes;
    }
  },

  /**
   * Accept subtask suggestions and create actual subtasks
   * Requirement 2.4: Create subtasks with appropriate priorities and link to parent
   */
  async acceptSuggestions(
    userId: string,
    parentTaskId: string,
    acceptedSuggestions: SubtaskSuggestion[]
  ): Promise<ServiceResult<Task[]>> {
    try {
      // Validate input
      const validated = AcceptSuggestionsSchema.parse({
        parentTaskId,
        suggestions: acceptedSuggestions,
      });

      // Verify parent task exists and belongs to user
      const parentTask = await prisma.task.findFirst({
        where: { id: validated.parentTaskId, userId },
      });

      if (!parentTask) {
        return {
          success: false,
          error: {
            code: 'NOT_FOUND',
            message: 'Parent task not found',
          },
        };
      }

      // Create subtasks
      const createdTasks: Task[] = [];
      
      for (const suggestion of validated.suggestions) {
        const result = await taskService.create(userId, {
          title: suggestion.title,
          projectId: parentTask.projectId,
          parentId: parentTask.id,
          priority: suggestion.priority,
          planDate: parentTask.planDate,
          estimatedMinutes: suggestion.estimatedMinutes,
        });

        if (result.success && result.data) {
          createdTasks.push(result.data);
        }
      }

      return {
        success: true,
        data: createdTasks,
      };
    } catch (error) {
      if (error instanceof z.ZodError) {
        return {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Invalid suggestion data',
            details: error.flatten().fieldErrors as Record<string, string[]>,
          },
        };
      }
      return {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: error instanceof Error ? error.message : 'Failed to accept suggestions',
        },
      };
    }
  },

  /**
   * Record user feedback on suggestions for learning
   * Requirement 2.5: Learn from user acceptance/rejection patterns
   */
  async recordFeedback(
    userId: string,
    taskId: string,
    suggestions: SubtaskSuggestion[],
    accepted: string[],
    rejected: string[]
  ): Promise<ServiceResult<void>> {
    try {
      // Validate input
      const validated = RecordFeedbackSchema.parse({
        taskId,
        suggestions,
        accepted,
        rejected,
      });

      // Verify task exists and belongs to user
      const task = await prisma.task.findFirst({
        where: { id: validated.taskId, userId },
      });

      if (!task) {
        return {
          success: false,
          error: {
            code: 'NOT_FOUND',
            message: 'Task not found',
          },
        };
      }

      // Store feedback in TaskDecompositionFeedback table
      await prisma.taskDecompositionFeedback.create({
        data: {
          userId,
          taskId: validated.taskId,
          suggestions: validated.suggestions,
          accepted: validated.accepted,
          rejected: validated.rejected,
        },
      });

      return { success: true, data: undefined };
    } catch (error) {
      if (error instanceof z.ZodError) {
        return {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Invalid feedback data',
            details: error.flatten().fieldErrors as Record<string, string[]>,
          },
        };
      }
      return {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: error instanceof Error ? error.message : 'Failed to record feedback',
        },
      };
    }
  },

  /**
   * Get feedback history for analysis
   * Used internally for improving suggestions
   */
  async getFeedbackHistory(
    userId: string,
    limit: number = 50
  ): Promise<ServiceResult<Array<{
    taskId: string;
    suggestions: SubtaskSuggestion[];
    accepted: string[];
    rejected: string[];
    createdAt: Date;
  }>>> {
    try {
      const feedback = await prisma.taskDecompositionFeedback.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        take: limit,
      });

      return {
        success: true,
        data: feedback.map(f => ({
          taskId: f.taskId,
          suggestions: f.suggestions as unknown as SubtaskSuggestion[],
          accepted: f.accepted,
          rejected: f.rejected,
          createdAt: f.createdAt,
        })),
      };
    } catch (error) {
      return {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: error instanceof Error ? error.message : 'Failed to get feedback history',
        },
      };
    }
  },

  /**
   * Analyze feedback patterns to improve future suggestions
   * Requirement 2.5: Learn from user acceptance/rejection patterns
   * 
   * Returns statistics about which types of suggestions are most accepted/rejected
   */
  async analyzeFeedbackPatterns(
    userId: string
  ): Promise<ServiceResult<{
    totalFeedback: number;
    acceptanceRate: number;
    commonAcceptedPatterns: string[];
    commonRejectedPatterns: string[];
    preferredPriorities: Record<string, number>;
  }>> {
    try {
      const feedbackResult = await this.getFeedbackHistory(userId, 100);
      
      if (!feedbackResult.success || !feedbackResult.data) {
        return {
          success: true,
          data: {
            totalFeedback: 0,
            acceptanceRate: 0,
            commonAcceptedPatterns: [],
            commonRejectedPatterns: [],
            preferredPriorities: {},
          },
        };
      }

      const feedback = feedbackResult.data;
      
      if (feedback.length === 0) {
        return {
          success: true,
          data: {
            totalFeedback: 0,
            acceptanceRate: 0,
            commonAcceptedPatterns: [],
            commonRejectedPatterns: [],
            preferredPriorities: {},
          },
        };
      }

      // Calculate acceptance rate
      let totalSuggestions = 0;
      let totalAccepted = 0;
      const acceptedKeywords: Record<string, number> = {};
      const rejectedKeywords: Record<string, number> = {};
      const priorityCounts: Record<string, number> = { P1: 0, P2: 0, P3: 0 };

      for (const f of feedback) {
        totalSuggestions += f.suggestions.length;
        totalAccepted += f.accepted.length;

        // Extract keywords from accepted suggestions
        for (const title of f.accepted) {
          const words = title.toLowerCase().split(/\s+/);
          for (const word of words) {
            if (word.length > 3) {
              acceptedKeywords[word] = (acceptedKeywords[word] || 0) + 1;
            }
          }
          
          // Track priority preferences
          const suggestion = f.suggestions.find(s => s.title === title);
          if (suggestion) {
            priorityCounts[suggestion.priority]++;
          }
        }

        // Extract keywords from rejected suggestions
        for (const title of f.rejected) {
          const words = title.toLowerCase().split(/\s+/);
          for (const word of words) {
            if (word.length > 3) {
              rejectedKeywords[word] = (rejectedKeywords[word] || 0) + 1;
            }
          }
        }
      }

      // Get top patterns
      const sortedAccepted = Object.entries(acceptedKeywords)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(([word]) => word);

      const sortedRejected = Object.entries(rejectedKeywords)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(([word]) => word);

      return {
        success: true,
        data: {
          totalFeedback: feedback.length,
          acceptanceRate: totalSuggestions > 0 ? totalAccepted / totalSuggestions : 0,
          commonAcceptedPatterns: sortedAccepted,
          commonRejectedPatterns: sortedRejected,
          preferredPriorities: priorityCounts,
        },
      };
    } catch (error) {
      return {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: error instanceof Error ? error.message : 'Failed to analyze feedback patterns',
        },
      };
    }
  },
};

export default taskDecomposerService;
