/**
 * Octopus Architecture - Unified Event and Command Protocol Types
 * 
 * This file defines the standardized communication protocol between
 * Vibe Brain (cloud core) and Tentacles (edge clients).
 */

// =============================================================================
// ENUMS
// =============================================================================

/**
 * Event types for Event Stream (Tentacle → Vibe Brain)
 */
export type EventType =
  | 'ACTIVITY_LOG'
  | 'STATE_CHANGE'
  | 'USER_ACTION'
  | 'HEARTBEAT'
  | 'TIMELINE_EVENT'
  | 'BLOCK_EVENT'
  | 'INTERRUPTION_EVENT'
  | 'BROWSER_ACTIVITY'
  | 'BROWSER_SESSION'
  | 'TAB_SWITCH'
  | 'BROWSER_FOCUS'
  | 'ENTERTAINMENT_MODE'
  | 'WORK_START'
  | 'CHAT_MESSAGE'
  | 'CHAT_ACTION';

/**
 * Client types for identifying the source/target of events and commands
 */
export type ClientType = 'web' | 'desktop' | 'browser_ext' | 'mobile';

/**
 * Command types for Command Stream (Vibe Brain → Tentacle)
 */
export type CommandType =
  | 'SYNC_STATE'
  | 'EXECUTE_ACTION'
  | 'UPDATE_POLICY'
  | 'SHOW_UI'
  | 'CHAT_RESPONSE'
  | 'CHAT_TOOL_CALL'
  | 'CHAT_TOOL_RESULT'
  | 'CHAT_SYNC';

/**
 * Action types that can be executed by clients
 */
export type ActionType =
  // Desktop actions
  | 'CLOSE_APP'
  | 'HIDE_APP'
  | 'BRING_TO_FRONT'
  | 'SHOW_NOTIFICATION'
  // Browser actions
  | 'CLOSE_TAB'
  | 'REDIRECT_TAB'
  | 'INJECT_OVERLAY'
  | 'ADD_SESSION_WHITELIST'
  // Mobile actions
  | 'SEND_PUSH'
  | 'PLAY_SOUND'
  | 'VIBRATE';

/**
 * Activity categories for productivity tracking
 */
export type ActivityCategory = 'productive' | 'neutral' | 'distracting';

/**
 * Activity source types
 */
export type ActivitySource = 'browser' | 'desktop_app' | 'mobile_app';

/**
 * Connection quality levels
 */
export type ConnectionQuality = 'good' | 'degraded' | 'poor';

/**
 * Navigation types for browser activity
 */
export type NavigationType = 'link' | 'typed' | 'reload' | 'back_forward' | 'other';

/**
 * Search engine types
 */
export type SearchEngine = 'google' | 'bing' | 'duckduckgo' | 'other';

/**
 * Browser focus states
 */
export type BrowserFocusState = 'focused' | 'blurred' | 'unknown';

/**
 * Interaction types for user engagement tracking
 */
export type InteractionType = 'click' | 'input' | 'scroll' | 'keypress' | 'video_play' | 'video_pause';

// =============================================================================
// EVENT STREAM TYPES (Tentacle → Vibe Brain)
// =============================================================================

/**
 * Base interface for all events from Tentacles to Vibe Brain
 * Requirements: 2.1, 2.3, 7.6
 */
export interface BaseEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: EventType;
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
}

/**
 * Activity log metadata
 */
export interface ActivityLogMetadata {
  domain?: string;
  appBundleId?: string;
  windowTitle?: string;
}

/**
 * Activity log payload
 * Requirements: 7.2
 */
export interface ActivityLogPayload {
  source: ActivitySource;
  /** URL or app bundle ID */
  identifier: string;
  /** Page title or app name */
  title: string;
  /** Duration in seconds */
  duration: number;
  category: ActivityCategory;
  metadata?: ActivityLogMetadata;
}

/**
 * Activity log from sensors (browser, desktop, mobile)
 * Requirements: 7.2
 */
export interface ActivityLogEvent extends BaseEvent {
  eventType: 'ACTIVITY_LOG';
  payload: ActivityLogPayload;
}

/**
 * State change payload
 * Requirements: 7.3
 */
export interface StateChangePayload {
  previousState: string;
  newState: string;
  trigger: string;
  timestamp: number;
}

/**
 * State change event
 * Requirements: 7.3
 */
export interface StateChangeEvent extends BaseEvent {
  eventType: 'STATE_CHANGE';
  payload: StateChangePayload;
}

/**
 * User action payload
 * Requirements: 7.4
 */
export interface UserActionPayload {
  actionType: string;
  targetEntity: string;
  parameters: Record<string, unknown>;
  result: string;
}

/**
 * User action event
 * Requirements: 7.4
 */
export interface UserActionEvent extends BaseEvent {
  eventType: 'USER_ACTION';
  payload: UserActionPayload;
}

/**
 * Heartbeat payload
 * Requirements: 7.5
 */
export interface HeartbeatPayload {
  clientVersion: string;
  /** Platform: 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'chrome' */
  platform: string;
  connectionQuality: ConnectionQuality;
  /** Hash of local state for conflict detection */
  localStateHash: string;
  /** Capabilities: ['sensor:app', 'action:close_app', etc.] */
  capabilities: string[];
  /** Seconds since client start */
  uptime: number;
}

/**
 * Periodic heartbeat from clients
 * Requirements: 7.5
 */
export interface HeartbeatEvent extends BaseEvent {
  eventType: 'HEARTBEAT';
  payload: HeartbeatPayload;
}

/**
 * Domain breakdown entry for browser sessions
 */
export interface DomainBreakdownEntry {
  domain: string;
  /** Duration in seconds */
  duration: number;
  /** Active duration in seconds */
  activeDuration: number;
  category: ActivityCategory;
  visitCount: number;
}

/**
 * Enhanced browser activity payload
 * Requirements: 5.6-5.20
 */
export interface BrowserActivityPayload {
  // Basic info
  url: string;
  title: string;
  domain: string;

  // Time tracking
  /** Unix timestamp (ms) */
  startTime: number;
  /** Unix timestamp (ms) */
  endTime: number;
  /** Total time on page (seconds) */
  duration: number;
  /** Time with user interaction (seconds) */
  activeDuration: number;
  /** Time without interaction (seconds) */
  idleTime: number;

  // Categorization
  category: ActivityCategory;
  /** 0-100 */
  productivityScore: number;

  // User engagement metrics
  /** 0-100 percentage */
  scrollDepth: number;
  /** clicks, inputs, etc. */
  interactionCount: number;

  // Media tracking
  isMediaPlaying: boolean;
  /** seconds */
  mediaPlayDuration: number;

  // Navigation context
  referrer?: string;
  navigationType: NavigationType;

  // Search tracking (for search engines)
  searchQuery?: string;
  searchEngine?: SearchEngine;
}

/**
 * Enhanced browser activity log with detailed tracking
 * Requirements: 5.6-5.20
 */
export interface BrowserActivityEvent extends BaseEvent {
  eventType: 'BROWSER_ACTIVITY';
  payload: BrowserActivityPayload;
}

/**
 * Browser session payload
 * Requirements: 5.13-5.17
 */
export interface BrowserSessionPayload {
  sessionId: string;
  startTime: number;
  endTime: number;
  /** seconds */
  totalDuration: number;
  /** seconds with browser focused */
  activeDuration: number;

  // Domain breakdown
  domainBreakdown: DomainBreakdownEntry[];

  // Behavior patterns
  tabSwitchCount: number;
  /** switches within 3 seconds */
  rapidTabSwitches: number;
  uniqueDomainsVisited: number;

  // Productivity summary
  productiveTime: number;
  distractingTime: number;
  neutralTime: number;
  /** 0-100 */
  productivityScore: number;
}

/**
 * Browser session summary event
 * Requirements: 5.13-5.17
 */
export interface BrowserSessionEvent extends BaseEvent {
  eventType: 'BROWSER_SESSION';
  payload: BrowserSessionPayload;
}

/**
 * Tab switch payload
 * Requirements: 5.3, 5.17
 */
export interface TabSwitchPayload {
  fromTabId: number;
  toTabId: number;
  fromUrl: string;
  toUrl: string;
  fromDomain: string;
  toDomain: string;
  /** milliseconds */
  timeSinceLastSwitch: number;
  /** < 3 seconds since last switch */
  isRapidSwitch: boolean;
}

/**
 * Tab switch event for distraction detection
 * Requirements: 5.3, 5.17
 */
export interface TabSwitchEvent extends BaseEvent {
  eventType: 'TAB_SWITCH';
  payload: TabSwitchPayload;
}

/**
 * Browser focus payload
 * Requirements: 5.9, 5.16
 */
export interface BrowserFocusPayload {
  /** true = browser gained focus, false = lost focus */
  isFocused: boolean;
  previousState: BrowserFocusState;
  /** seconds (only when losing focus) */
  focusDuration?: number;
}

/**
 * Browser focus event
 * Requirements: 5.9, 5.16
 */
export interface BrowserFocusEvent extends BaseEvent {
  eventType: 'BROWSER_FOCUS';
  payload: BrowserFocusPayload;
}

// =============================================================================
// ENTERTAINMENT MODE EVENT (Requirements 8.6, 10.3, 12.1, 12.2)
// =============================================================================

/**
 * Entertainment mode stop reason
 */
export type EntertainmentStopReason = 'manual' | 'quota_exhausted' | 'work_time_start';

/**
 * Entertainment mode event payload
 * Requirements: 8.6, 10.3, 12.1, 12.2
 */
export interface EntertainmentModePayload {
  action: 'start' | 'stop';
  sessionId: string;
  timestamp: number;
  quotaUsedBefore: number;   // minutes
  quotaUsedAfter?: number;   // minutes (only for stop)
  duration?: number;         // seconds (only for stop)
  sitesVisited?: string[];   // domains visited during session
  reason?: EntertainmentStopReason;
}

/**
 * Entertainment mode event
 * Requirements: 8.6, 10.3, 12.1, 12.2
 */
export interface EntertainmentModeEvent extends BaseEvent {
  eventType: 'ENTERTAINMENT_MODE';
  payload: EntertainmentModePayload;
}

// =============================================================================
// WORK START EVENT (Requirements 14.1, 14.2, 14.9, 14.10)
// =============================================================================

/**
 * Work start event payload
 * Requirements: 14.1, 14.2, 14.9, 14.10
 */
export interface WorkStartPayload {
  date: string;                  // YYYY-MM-DD
  configuredStartTime: string;   // HH:mm
  actualStartTime: number;       // Unix timestamp
  delayMinutes: number;          // 0 if on-time or early, positive if late
  trigger: 'airlock_complete';   // What triggered the work start
}

/**
 * Work start event
 * Requirements: 14.1, 14.2, 14.9, 14.10
 */
export interface WorkStartEvent extends BaseEvent {
  eventType: 'WORK_START';
  payload: WorkStartPayload;
}

// ---- AI Chat Events ----

export interface ChatAttachment {
  type: 'task' | 'project' | 'goal' | 'pomodoro';
  id: string;
  title: string;
}

export interface ChatMessagePayload {
  conversationId: string;
  messageId: string;
  content: string;
  attachments?: ChatAttachment[];
}

export interface ChatMessageEvent extends BaseEvent {
  eventType: 'CHAT_MESSAGE';
  payload: ChatMessagePayload;
}

export interface ChatActionPayload {
  conversationId: string;
  toolCallId: string;
  action: 'confirm' | 'cancel';
}

export interface ChatActionEvent extends BaseEvent {
  eventType: 'CHAT_ACTION';
  payload: ChatActionPayload;
}

/**
 * Union type for all event types
 */
export type OctopusEvent =
  | ActivityLogEvent
  | StateChangeEvent
  | UserActionEvent
  | HeartbeatEvent
  | BrowserActivityEvent
  | BrowserSessionEvent
  | TabSwitchEvent
  | BrowserFocusEvent
  | EntertainmentModeEvent
  | WorkStartEvent
  | ChatMessageEvent
  | ChatActionEvent;


// =============================================================================
// COMMAND STREAM TYPES (Vibe Brain → Tentacle)
// =============================================================================

/**
 * Command priority levels
 */
export type CommandPriority = 'low' | 'normal' | 'high' | 'critical';

/**
 * Base interface for all commands from Vibe Brain to Tentacles
 * Requirements: 2.2, 2.4, 8.6
 */
export interface BaseCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: CommandType;
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
}

/**
 * System state for full sync
 */
export interface SystemState {
  state: string;
  dailyCapReached: boolean;
  skipTokensRemaining: number;
}

/**
 * Daily state for full sync
 */
export interface DailyState {
  date: string;
  completedPomodoros: number;
  totalFocusMinutes: number;
  top3TaskIds: string[];
}

/**
 * Pomodoro state for full sync
 */
export interface PomodoroState {
  id: string;
  taskId: string | null;
  taskTitle?: string | null;
  startTime: number;
  duration: number;
  status: 'active' | 'paused' | 'completed' | 'aborted';
}

/**
 * Task state for full sync
 */
export interface TaskState {
  id: string;
  title: string;
  status: string;
  priority: string;
}

/**
 * User settings for full sync
 */
export interface UserSettingsState {
  pomodoroDuration: number;
  shortBreakDuration: number;
  longBreakDuration: number;
  dailyCap: number;
  enforcementMode: 'strict' | 'gentle';
}

/**
 * Full state for sync
 * Requirements: 8.2
 */
export interface FullState {
  systemState: SystemState;
  dailyState: DailyState;
  activePomodoro: PomodoroState | null;
  top3Tasks: TaskState[];
  settings: UserSettingsState;
}

/**
 * State delta change entry
 */
export interface StateDeltaChange {
  /** JSON path */
  path: string;
  operation: 'set' | 'delete';
  value?: unknown;
}

/**
 * State delta for incremental sync
 * Requirements: 8.2
 */
export interface StateDelta {
  changes: StateDeltaChange[];
}

/**
 * Sync state payload
 * Requirements: 8.2
 */
export interface SyncStatePayload {
  syncType: 'full' | 'delta';
  version: number;
  /** For full sync */
  state?: FullState;
  /** For delta sync */
  delta?: StateDelta;
}

/**
 * Synchronize state to clients
 * Requirements: 8.2
 */
export interface SyncStateCommand extends BaseCommand {
  commandType: 'SYNC_STATE';
  payload: SyncStatePayload;
}

/**
 * Execute action payload
 * Requirements: 8.3
 */
export interface ExecuteActionPayload {
  action: ActionType;
  parameters: Record<string, unknown>;
  /** Milliseconds */
  timeout?: number;
  fallbackAction?: ActionType;
}

/**
 * Execute an action on client
 * Requirements: 8.3
 */
export interface ExecuteActionCommand extends BaseCommand {
  commandType: 'EXECUTE_ACTION';
  payload: ExecuteActionPayload;
}

/**
 * Update policy payload
 * Requirements: 8.4
 */
export interface UpdatePolicyPayload {
  policyType: 'full' | 'partial';
  policy: Policy;
  /** When policy takes effect */
  effectiveTime: number;
}

/**
 * Update policy on client
 * Requirements: 8.4
 */
export interface UpdatePolicyCommand extends BaseCommand {
  commandType: 'UPDATE_POLICY';
  payload: UpdatePolicyPayload;
}

/**
 * UI types for show UI command
 */
export type UIType = 'notification' | 'modal' | 'overlay' | 'toast';

/**
 * Show UI payload
 * Requirements: 8.5
 */
export interface ShowUIPayload {
  uiType: UIType;
  content: Record<string, unknown>;
  /** Duration in milliseconds */
  duration?: number;
  dismissible: boolean;
}

/**
 * Show UI on client
 * Requirements: 8.5
 */
export interface ShowUICommand extends BaseCommand {
  commandType: 'SHOW_UI';
  payload: ShowUIPayload;
}

// ---- AI Chat Commands ----

export interface ChatResponsePayload {
  conversationId: string;
  messageId: string;
  type: 'delta' | 'complete';
  content: string;
  usage?: { inputTokens: number; outputTokens: number };
  /** True when message is an AI-initiated proactive push (S4) */
  isProactive?: boolean;
  /** Trigger that generated this proactive message (S4) */
  triggerId?: string;
}

export interface ChatResponseCommand extends BaseCommand {
  commandType: 'CHAT_RESPONSE';
  payload: ChatResponsePayload;
}

export interface ChatToolCallPayload {
  conversationId: string;
  messageId: string;
  toolCallId: string;
  toolName: string;
  description: string;
  parameters: Record<string, unknown>;
  requiresConfirmation: boolean;
}

export interface ChatToolCallCommand extends BaseCommand {
  commandType: 'CHAT_TOOL_CALL';
  payload: ChatToolCallPayload;
}

export interface ChatToolResultPayload {
  conversationId: string;
  messageId: string;
  toolCallId: string;
  success: boolean;
  summary: string;
}

export interface ChatToolResultCommand extends BaseCommand {
  commandType: 'CHAT_TOOL_RESULT';
  payload: ChatToolResultPayload;
}

export interface ChatSyncPayload {
  conversationId: string;
  messages: Array<{
    id: string;
    role: string;
    content: string;
    metadata?: Record<string, unknown>;
    createdAt: string;
  }>;
}

export interface ChatSyncCommand extends BaseCommand {
  commandType: 'CHAT_SYNC';
  payload: ChatSyncPayload;
}

/**
 * Union type for all command types
 */
export type OctopusCommand =
  | SyncStateCommand
  | ExecuteActionCommand
  | UpdatePolicyCommand
  | ShowUICommand
  | ChatResponseCommand
  | ChatToolCallCommand
  | ChatToolResultCommand
  | ChatSyncCommand;

// =============================================================================
// POLICY TYPES
// =============================================================================

/**
 * Time slot for work time configuration
 * Requirements: 10.5
 */
export interface TimeSlot {
  /** 0-6 (Sunday = 0) */
  dayOfWeek: number;
  startHour: number;
  startMinute: number;
  endHour: number;
  endMinute: number;
}

/**
 * Skip token configuration
 * Requirements: 10.5
 */
export interface SkipTokenConfig {
  remaining: number;
  maxPerDay: number;
  delayMinutes: number;
}

/**
 * Distraction app configuration
 * Requirements: 10.5
 */
export interface DistractionApp {
  bundleId: string;
  name: string;
  action: 'force_quit' | 'hide_window';
}

/**
 * Enforcement mode for policy
 */
export type EnforcementMode = 'strict' | 'gentle';

/**
 * Ad-hoc focus session configuration for policy
 * Requirements: 2.3, 13.1, 13.2
 */
export interface AdhocFocusSession {
  /** Whether an ad-hoc focus session is currently active */
  active: boolean;
  /** Unix timestamp when the session ends */
  endTime: number;
  /** Whether this session overrides sleep time enforcement */
  overridesSleepTime?: boolean;
}

/**
 * Sleep enforcement app configuration for policy
 * Requirements: 11.1
 */
export interface SleepEnforcementAppPolicy {
  bundleId: string;
  name: string;
}

/**
 * Sleep time configuration for policy
 * Requirements: 9.4, 11.1, 11.2
 */
export interface SleepTimePolicy {
  /** Whether sleep time enforcement is enabled */
  enabled: boolean;
  /** Sleep start time in "HH:mm" format */
  startTime: string;
  /** Sleep end time in "HH:mm" format */
  endTime: string;
  /** Apps to close during sleep time */
  enforcementApps: SleepEnforcementAppPolicy[];
  /** Whether currently within the sleep time window */
  isCurrentlyActive: boolean;
  /** Whether sleep enforcement is currently snoozed */
  isSnoozed: boolean;
  /** Unix timestamp when snooze ends (if snoozed) */
  snoozeEndTime?: number;
}

/**
 * Over rest configuration for policy
 * Requirements: 15.2, 15.3, 16.1-16.5
 */
export interface OverRestPolicy {
  /** Whether user is currently in over rest state */
  isOverRest: boolean;
  /** Minutes over the normal rest duration */
  overRestMinutes: number;
  /** Apps to close during over rest */
  enforcementApps: SleepEnforcementAppPolicy[];
  /** Whether to bring app to front */
  bringToFront: boolean;
}

/**
 * Policy object distributed to clients
 * Requirements: 10.5, 10.6
 */
export interface Policy {
  version: number;
  blacklist: string[];
  whitelist: string[];
  enforcementMode: EnforcementMode;
  workTimeSlots: TimeSlot[];
  skipTokens: SkipTokenConfig;
  distractionApps: DistractionApp[];
  /** Unix timestamp */
  updatedAt: number;
  /** Ad-hoc focus session configuration (optional) */
  adhocFocusSession?: AdhocFocusSession;
  /** Sleep time configuration (optional) */
  sleepTime?: SleepTimePolicy;
  /** Over rest configuration (optional) */
  overRest?: OverRestPolicy;
}

// =============================================================================
// CLIENT REGISTRY TYPES
// =============================================================================

/**
 * Client connection information
 */
export interface ClientConnection {
  socketId: string;
  userId: string;
  clientType: ClientType;
  clientVersion: string;
  platform: string;
  capabilities: string[];
}

/**
 * Client metadata
 */
export interface ClientMetadata {
  clientVersion: string;
  platform: string;
  capabilities: string[];
  deviceName?: string;
  localStateHash?: string;
}

/**
 * Client status
 */
export type ClientStatus = 'online' | 'offline';

/**
 * Registered client information
 */
export interface RegisteredClient {
  clientId: string;
  userId: string;
  clientType: ClientType;
  metadata: ClientMetadata;
  status: ClientStatus;
  lastSeenAt: number;
  registeredAt: number;
}

// =============================================================================
// COMMAND QUEUE TYPES
// =============================================================================

/**
 * Command queue status
 */
export type CommandQueueStatus = 'pending' | 'delivered' | 'acknowledged' | 'expired';

/**
 * Queue statistics
 */
export interface QueueStats {
  pendingCount: number;
  deliveredCount: number;
  acknowledgedCount: number;
  expiredCount: number;
}

// =============================================================================
// ERROR TYPES
// =============================================================================

/**
 * Error codes for protocol errors
 */
export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'AUTH_ERROR'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'INTERNAL_ERROR';

/**
 * Error response structure
 */
export interface ErrorResponse {
  success: false;
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
    retryable: boolean;
    /** Seconds */
    retryAfter?: number;
  };
}


// =============================================================================
// ZOD SCHEMAS FOR VALIDATION
// =============================================================================

import { z } from 'zod';

// Event type enum schema
export const EventTypeSchema = z.enum([
  'ACTIVITY_LOG',
  'STATE_CHANGE',
  'USER_ACTION',
  'HEARTBEAT',
  'TIMELINE_EVENT',
  'BLOCK_EVENT',
  'INTERRUPTION_EVENT',
  'BROWSER_ACTIVITY',
  'BROWSER_SESSION',
  'TAB_SWITCH',
  'BROWSER_FOCUS',
  'ENTERTAINMENT_MODE',
  'WORK_START',
  'CHAT_MESSAGE',
  'CHAT_ACTION',
]);

// Client type enum schema
export const ClientTypeSchema = z.enum(['web', 'desktop', 'browser_ext', 'mobile']);

// Command type enum schema
export const CommandTypeSchema = z.enum([
  'SYNC_STATE',
  'EXECUTE_ACTION',
  'UPDATE_POLICY',
  'SHOW_UI',
  'CHAT_RESPONSE',
  'CHAT_TOOL_CALL',
  'CHAT_TOOL_RESULT',
  'CHAT_SYNC',
]);

// Action type enum schema
export const ActionTypeSchema = z.enum([
  'CLOSE_APP',
  'HIDE_APP',
  'BRING_TO_FRONT',
  'SHOW_NOTIFICATION',
  'CLOSE_TAB',
  'REDIRECT_TAB',
  'INJECT_OVERLAY',
  'ADD_SESSION_WHITELIST',
  'SEND_PUSH',
  'PLAY_SOUND',
  'VIBRATE',
]);

// Activity category schema
export const ActivityCategorySchema = z.enum(['productive', 'neutral', 'distracting']);

// Connection quality schema
export const ConnectionQualitySchema = z.enum(['good', 'degraded', 'poor']);

// Navigation type schema
export const NavigationTypeSchema = z.enum(['link', 'typed', 'reload', 'back_forward', 'other']);

// Search engine schema
export const SearchEngineSchema = z.enum(['google', 'bing', 'duckduckgo', 'other']);

// Browser focus state schema
export const BrowserFocusStateSchema = z.enum(['focused', 'blurred', 'unknown']);

// Base event schema (validates required fields)
export const BaseEventSchema = z.object({
  eventId: z.string().uuid(),
  eventType: EventTypeSchema,
  userId: z.string().min(1),
  clientId: z.string().min(1),
  clientType: ClientTypeSchema,
  timestamp: z.number().int().positive(),
  sequenceNumber: z.number().int().nonnegative(),
});

// Activity log payload schema
export const ActivityLogPayloadSchema = z.object({
  source: z.enum(['browser', 'desktop_app', 'mobile_app']),
  identifier: z.string().min(1),
  title: z.string(),
  duration: z.number().nonnegative(),
  category: ActivityCategorySchema,
  metadata: z.object({
    domain: z.string().optional(),
    appBundleId: z.string().optional(),
    windowTitle: z.string().optional(),
  }).optional(),
});

// Activity log event schema
export const ActivityLogEventSchema = BaseEventSchema.extend({
  eventType: z.literal('ACTIVITY_LOG'),
  payload: ActivityLogPayloadSchema,
});

// State change payload schema
export const StateChangePayloadSchema = z.object({
  previousState: z.string(),
  newState: z.string(),
  trigger: z.string(),
  timestamp: z.number().int().positive(),
});

// State change event schema
export const StateChangeEventSchema = BaseEventSchema.extend({
  eventType: z.literal('STATE_CHANGE'),
  payload: StateChangePayloadSchema,
});

// User action payload schema (supports both legacy and mobile client formats)
export const UserActionPayloadSchema = z.object({
  actionType: z.string(),
  targetEntity: z.string().optional(),
  parameters: z.record(z.unknown()).optional(),
  result: z.string().optional(),
  // Mobile client fields
  optimisticId: z.string().optional(),
  data: z.record(z.unknown()).optional(),
});

// User action event schema
export const UserActionEventSchema = BaseEventSchema.extend({
  eventType: z.literal('USER_ACTION'),
  payload: UserActionPayloadSchema,
});

// Heartbeat payload schema
export const HeartbeatPayloadSchema = z.object({
  clientVersion: z.string().min(1),
  platform: z.string().min(1),
  connectionQuality: ConnectionQualitySchema,
  localStateHash: z.string(),
  capabilities: z.array(z.string()),
  uptime: z.number().nonnegative(),
});

// Heartbeat event schema
export const HeartbeatEventSchema = BaseEventSchema.extend({
  eventType: z.literal('HEARTBEAT'),
  payload: HeartbeatPayloadSchema,
});

// Browser activity payload schema
export const BrowserActivityPayloadSchema = z.object({
  url: z.string().url(),
  title: z.string(),
  domain: z.string(),
  startTime: z.number().int().positive(),
  endTime: z.number().int().positive(),
  duration: z.number().nonnegative(),
  activeDuration: z.number().nonnegative(),
  idleTime: z.number().nonnegative(),
  category: ActivityCategorySchema,
  productivityScore: z.number().min(0).max(100),
  scrollDepth: z.number().min(0).max(100),
  interactionCount: z.number().int().nonnegative(),
  isMediaPlaying: z.boolean(),
  mediaPlayDuration: z.number().nonnegative(),
  referrer: z.string().optional(),
  navigationType: NavigationTypeSchema,
  searchQuery: z.string().optional(),
  searchEngine: SearchEngineSchema.optional(),
});

// Browser activity event schema
export const BrowserActivityEventSchema = BaseEventSchema.extend({
  eventType: z.literal('BROWSER_ACTIVITY'),
  payload: BrowserActivityPayloadSchema,
});

// Domain breakdown entry schema
export const DomainBreakdownEntrySchema = z.object({
  domain: z.string(),
  duration: z.number().nonnegative(),
  activeDuration: z.number().nonnegative(),
  category: ActivityCategorySchema,
  visitCount: z.number().int().positive(),
});

// Browser session payload schema
export const BrowserSessionPayloadSchema = z.object({
  sessionId: z.string().min(1),
  startTime: z.number().int().positive(),
  endTime: z.number().int().positive(),
  totalDuration: z.number().nonnegative(),
  activeDuration: z.number().nonnegative(),
  domainBreakdown: z.array(DomainBreakdownEntrySchema),
  tabSwitchCount: z.number().int().nonnegative(),
  rapidTabSwitches: z.number().int().nonnegative(),
  uniqueDomainsVisited: z.number().int().nonnegative(),
  productiveTime: z.number().nonnegative(),
  distractingTime: z.number().nonnegative(),
  neutralTime: z.number().nonnegative(),
  productivityScore: z.number().min(0).max(100),
});

// Browser session event schema
export const BrowserSessionEventSchema = BaseEventSchema.extend({
  eventType: z.literal('BROWSER_SESSION'),
  payload: BrowserSessionPayloadSchema,
});

// Tab switch payload schema
export const TabSwitchPayloadSchema = z.object({
  fromTabId: z.number().int(),
  toTabId: z.number().int(),
  fromUrl: z.string(),
  toUrl: z.string(),
  fromDomain: z.string(),
  toDomain: z.string(),
  timeSinceLastSwitch: z.number().nonnegative(),
  isRapidSwitch: z.boolean(),
});

// Tab switch event schema
export const TabSwitchEventSchema = BaseEventSchema.extend({
  eventType: z.literal('TAB_SWITCH'),
  payload: TabSwitchPayloadSchema,
});

// Browser focus payload schema
export const BrowserFocusPayloadSchema = z.object({
  isFocused: z.boolean(),
  previousState: BrowserFocusStateSchema,
  focusDuration: z.number().nonnegative().optional(),
});

// Browser focus event schema
export const BrowserFocusEventSchema = BaseEventSchema.extend({
  eventType: z.literal('BROWSER_FOCUS'),
  payload: BrowserFocusPayloadSchema,
});

// Entertainment stop reason schema
export const EntertainmentStopReasonSchema = z.enum(['manual', 'quota_exhausted', 'work_time_start']);

// Entertainment mode payload schema
// Requirements: 8.6, 10.3, 12.1, 12.2
export const EntertainmentModePayloadSchema = z.object({
  action: z.enum(['start', 'stop']),
  sessionId: z.string().min(1),
  timestamp: z.number().int().positive(),
  quotaUsedBefore: z.number().nonnegative(),
  quotaUsedAfter: z.number().nonnegative().optional(),
  duration: z.number().nonnegative().optional(),
  sitesVisited: z.array(z.string()).optional(),
  reason: EntertainmentStopReasonSchema.optional(),
});

// Entertainment mode event schema
// Requirements: 8.6, 10.3, 12.1, 12.2
export const EntertainmentModeEventSchema = BaseEventSchema.extend({
  eventType: z.literal('ENTERTAINMENT_MODE'),
  payload: EntertainmentModePayloadSchema,
});

// Work start payload schema
// Requirements: 14.1, 14.2, 14.9, 14.10
export const WorkStartPayloadSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format. Use YYYY-MM-DD'),
  configuredStartTime: z.string().regex(/^([01]\d|2[0-3]):([0-5]\d)$/, 'Invalid time format. Use HH:mm'),
  actualStartTime: z.number().int().positive(),
  delayMinutes: z.number().int().nonnegative(),
  trigger: z.literal('airlock_complete'),
});

// Work start event schema
// Requirements: 14.1, 14.2, 14.9, 14.10
export const WorkStartEventSchema = BaseEventSchema.extend({
  eventType: z.literal('WORK_START'),
  payload: WorkStartPayloadSchema,
});

// ---- AI Chat Event Schemas ----

export const ChatAttachmentSchema = z.object({
  type: z.enum(['task', 'project', 'goal', 'pomodoro']),
  id: z.string(),
  title: z.string(),
});

export const ChatMessagePayloadSchema = z.object({
  conversationId: z.string(),
  messageId: z.string(),
  content: z.string(),
  attachments: z.array(ChatAttachmentSchema).optional(),
});

export const ChatMessageEventSchema = BaseEventSchema.extend({
  eventType: z.literal('CHAT_MESSAGE'),
  payload: ChatMessagePayloadSchema,
});

export const ChatActionPayloadSchema = z.object({
  conversationId: z.string(),
  toolCallId: z.string(),
  action: z.enum(['confirm', 'cancel']),
});

export const ChatActionEventSchema = BaseEventSchema.extend({
  eventType: z.literal('CHAT_ACTION'),
  payload: ChatActionPayloadSchema,
});

// Union schema for all events
export const OctopusEventSchema = z.discriminatedUnion('eventType', [
  ActivityLogEventSchema,
  StateChangeEventSchema,
  UserActionEventSchema,
  HeartbeatEventSchema,
  BrowserActivityEventSchema,
  BrowserSessionEventSchema,
  TabSwitchEventSchema,
  BrowserFocusEventSchema,
  EntertainmentModeEventSchema,
  WorkStartEventSchema,
  ChatMessageEventSchema,
  ChatActionEventSchema,
]);

// =============================================================================
// COMMAND SCHEMAS
// =============================================================================

// Command priority schema
export const CommandPrioritySchema = z.enum(['low', 'normal', 'high', 'critical']);

// Base command schema
export const BaseCommandSchema = z.object({
  commandId: z.string().uuid(),
  commandType: CommandTypeSchema,
  targetClient: z.union([ClientTypeSchema, z.literal('all')]),
  priority: CommandPrioritySchema,
  requiresAck: z.boolean(),
  expiryTime: z.number().int().positive().optional(),
  createdAt: z.number().int().positive(),
});

// System state schema
export const SystemStateSchema = z.object({
  state: z.string(),
  dailyCapReached: z.boolean(),
  skipTokensRemaining: z.number().int().nonnegative(),
});

// Daily state schema
export const DailyStateSchema = z.object({
  date: z.string(),
  completedPomodoros: z.number().int().nonnegative(),
  totalFocusMinutes: z.number().nonnegative(),
  top3TaskIds: z.array(z.string()),
});

// Pomodoro state schema
export const PomodoroStateSchema = z.object({
  id: z.string(),
  taskId: z.string(),
  startTime: z.number().int().positive(),
  duration: z.number().positive(),
  status: z.enum(['active', 'paused', 'completed', 'aborted']),
});

// Task state schema
export const TaskStateSchema = z.object({
  id: z.string(),
  title: z.string(),
  status: z.string(),
  priority: z.string(),
});

// User settings state schema
export const UserSettingsStateSchema = z.object({
  pomodoroDuration: z.number().positive(),
  shortBreakDuration: z.number().positive(),
  longBreakDuration: z.number().positive(),
  dailyCap: z.number().int().positive(),
  enforcementMode: z.enum(['strict', 'gentle']),
});

// Full state schema
export const FullStateSchema = z.object({
  systemState: SystemStateSchema,
  dailyState: DailyStateSchema,
  activePomodoro: PomodoroStateSchema.nullable(),
  top3Tasks: z.array(TaskStateSchema),
  settings: UserSettingsStateSchema,
});

// State delta change schema
export const StateDeltaChangeSchema = z.object({
  path: z.string(),
  operation: z.enum(['set', 'delete']),
  value: z.unknown().optional(),
});

// State delta schema
export const StateDeltaSchema = z.object({
  changes: z.array(StateDeltaChangeSchema),
});

// Sync state payload schema
export const SyncStatePayloadSchema = z.object({
  syncType: z.enum(['full', 'delta']),
  version: z.number().int().positive(),
  state: FullStateSchema.optional(),
  delta: StateDeltaSchema.optional(),
});

// Sync state command schema
export const SyncStateCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('SYNC_STATE'),
  payload: SyncStatePayloadSchema,
});

// Execute action payload schema
export const ExecuteActionPayloadSchema = z.object({
  action: ActionTypeSchema,
  parameters: z.record(z.unknown()),
  timeout: z.number().positive().optional(),
  fallbackAction: ActionTypeSchema.optional(),
});

// Execute action command schema
export const ExecuteActionCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('EXECUTE_ACTION'),
  payload: ExecuteActionPayloadSchema,
});

// Time slot schema
export const TimeSlotSchema = z.object({
  dayOfWeek: z.number().int().min(0).max(6),
  startHour: z.number().int().min(0).max(23),
  startMinute: z.number().int().min(0).max(59),
  endHour: z.number().int().min(0).max(23),
  endMinute: z.number().int().min(0).max(59),
});

// Skip token config schema
export const SkipTokenConfigSchema = z.object({
  remaining: z.number().int().nonnegative(),
  maxPerDay: z.number().int().positive(),
  delayMinutes: z.number().positive(),
});

// Distraction app schema
export const DistractionAppSchema = z.object({
  bundleId: z.string().min(1),
  name: z.string().min(1),
  action: z.enum(['force_quit', 'hide_window']),
});

// Ad-hoc focus session schema
// Requirements: 2.3, 13.1, 13.2
export const AdhocFocusSessionSchema = z.object({
  active: z.boolean(),
  endTime: z.number().int().positive(),
  overridesSleepTime: z.boolean().optional(),
});

// Sleep enforcement app schema for policy
export const SleepEnforcementAppPolicySchema = z.object({
  bundleId: z.string().min(1),
  name: z.string().min(1),
});

// Sleep time policy schema
// Requirements: 9.4, 11.1, 11.2
export const SleepTimePolicySchema = z.object({
  enabled: z.boolean(),
  startTime: z.string().regex(/^([01]\d|2[0-3]):([0-5]\d)$/, 'Invalid time format. Use HH:mm'),
  endTime: z.string().regex(/^([01]\d|2[0-3]):([0-5]\d)$/, 'Invalid time format. Use HH:mm'),
  enforcementApps: z.array(SleepEnforcementAppPolicySchema),
  isCurrentlyActive: z.boolean(),
  isSnoozed: z.boolean(),
  snoozeEndTime: z.number().int().positive().optional(),
});

// Over rest policy schema
// Requirements: 15.2, 15.3, 16.1-16.5
export const OverRestPolicySchema = z.object({
  isOverRest: z.boolean(),
  overRestMinutes: z.number().int().nonnegative(),
  enforcementApps: z.array(SleepEnforcementAppPolicySchema),
  bringToFront: z.boolean(),
});

// Policy schema
export const PolicySchema = z.object({
  version: z.number().int().positive(),
  blacklist: z.array(z.string()),
  whitelist: z.array(z.string()),
  enforcementMode: z.enum(['strict', 'gentle']),
  workTimeSlots: z.array(TimeSlotSchema),
  skipTokens: SkipTokenConfigSchema,
  distractionApps: z.array(DistractionAppSchema),
  updatedAt: z.number().int().positive(),
  adhocFocusSession: AdhocFocusSessionSchema.optional(),
  sleepTime: SleepTimePolicySchema.optional(),
  overRest: OverRestPolicySchema.optional(),
});

// Update policy payload schema
export const UpdatePolicyPayloadSchema = z.object({
  policyType: z.enum(['full', 'partial']),
  policy: PolicySchema,
  effectiveTime: z.number().int().positive(),
});

// Update policy command schema
export const UpdatePolicyCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('UPDATE_POLICY'),
  payload: UpdatePolicyPayloadSchema,
});

// UI type schema
export const UITypeSchema = z.enum(['notification', 'modal', 'overlay', 'toast']);

// Show UI payload schema
export const ShowUIPayloadSchema = z.object({
  uiType: UITypeSchema,
  content: z.record(z.unknown()),
  duration: z.number().positive().optional(),
  dismissible: z.boolean(),
});

// Show UI command schema
export const ShowUICommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('SHOW_UI'),
  payload: ShowUIPayloadSchema,
});

// Union schema for all commands
// ---- AI Chat Command Schemas ----

export const ChatResponsePayloadSchema = z.object({
  conversationId: z.string(),
  messageId: z.string(),
  type: z.enum(['delta', 'complete']),
  content: z.string(),
  usage: z.object({
    inputTokens: z.number(),
    outputTokens: z.number(),
  }).optional(),
  isProactive: z.boolean().optional(),
  triggerId: z.string().optional(),
});

export const ChatResponseCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('CHAT_RESPONSE'),
  payload: ChatResponsePayloadSchema,
});

export const ChatToolCallPayloadSchema = z.object({
  conversationId: z.string(),
  messageId: z.string(),
  toolCallId: z.string(),
  toolName: z.string(),
  description: z.string(),
  parameters: z.record(z.unknown()),
  requiresConfirmation: z.boolean(),
});

export const ChatToolCallCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('CHAT_TOOL_CALL'),
  payload: ChatToolCallPayloadSchema,
});

export const ChatToolResultPayloadSchema = z.object({
  conversationId: z.string(),
  messageId: z.string(),
  toolCallId: z.string(),
  success: z.boolean(),
  summary: z.string(),
});

export const ChatToolResultCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('CHAT_TOOL_RESULT'),
  payload: ChatToolResultPayloadSchema,
});

export const ChatSyncPayloadSchema = z.object({
  conversationId: z.string(),
  messages: z.array(z.object({
    id: z.string(),
    role: z.string(),
    content: z.string(),
    metadata: z.record(z.unknown()).optional(),
    createdAt: z.string(),
  })),
});

export const ChatSyncCommandSchema = BaseCommandSchema.extend({
  commandType: z.literal('CHAT_SYNC'),
  payload: ChatSyncPayloadSchema,
});

export const OctopusCommandSchema = z.discriminatedUnion('commandType', [
  SyncStateCommandSchema,
  ExecuteActionCommandSchema,
  UpdatePolicyCommandSchema,
  ShowUICommandSchema,
  ChatResponseCommandSchema,
  ChatToolCallCommandSchema,
  ChatToolResultCommandSchema,
  ChatSyncCommandSchema,
]);

// =============================================================================
// VALIDATION FUNCTIONS
// =============================================================================

/**
 * Validate an event against the schema
 */
export function validateEvent(event: unknown): { success: true; data: OctopusEvent } | { success: false; error: { code: ErrorCode; message: string; details?: Record<string, unknown> } } {
  const result = OctopusEventSchema.safeParse(event);
  if (result.success) {
    return { success: true, data: result.data as OctopusEvent };
  }
  return {
    success: false,
    error: {
      code: 'VALIDATION_ERROR',
      message: 'Invalid event format',
      details: { issues: result.error.issues },
    },
  };
}

/**
 * Validate a command against the schema
 */
export function validateCommand(command: unknown): { success: true; data: OctopusCommand } | { success: false; error: { code: ErrorCode; message: string; details?: Record<string, unknown> } } {
  const result = OctopusCommandSchema.safeParse(command);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return {
    success: false,
    error: {
      code: 'VALIDATION_ERROR',
      message: 'Invalid command format',
      details: { issues: result.error.issues },
    },
  };
}

/**
 * Validate a policy against the schema
 */
export function validatePolicy(policy: unknown): { success: true; data: Policy } | { success: false; error: { code: ErrorCode; message: string; details?: Record<string, unknown> } } {
  const result = PolicySchema.safeParse(policy);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return {
    success: false,
    error: {
      code: 'VALIDATION_ERROR',
      message: 'Invalid policy format',
      details: { issues: result.error.issues },
    },
  };
}
