/**
 * Octopus Architecture - Event Types
 *
 * Event Stream types (Tentacle -> Vibe Brain).
 */
import type { ChatMessageEvent, ChatActionEvent, ChatHistoryRequestEvent } from './chat';
import type { EventType, ClientType, ActivitySource, ActivityCategory, ConnectionQuality, NavigationType, SearchEngine, BrowserFocusState, EntertainmentStopReason } from './enums';
/**
 * Base interface for all events from Tentacles to Vibe Brain
 * Requirements: 2.1, 2.3, 7.6
 */
export interface BaseEvent {
    /** UUID, generated by client */
    eventId: string;
    /** Event type discriminator */
    eventType: EventType;
    /** User identifier */
    userId: string;
    /** Unique client instance ID */
    clientId: string;
    /** Client type identifier */
    clientType: ClientType;
    /** Unix timestamp (ms) */
    timestamp: number;
    /** Monotonic counter per client */
    sequenceNumber: number;
}
/**
 * Activity log metadata
 */
export interface ActivityLogMetadata {
    domain?: string;
    appBundleId?: string;
    windowTitle?: string;
}
/**
 * Activity log payload
 * Requirements: 7.2
 */
export interface ActivityLogPayload {
    source: ActivitySource;
    /** URL or app bundle ID */
    identifier: string;
    /** Page title or app name */
    title: string;
    /** Duration in seconds */
    duration: number;
    category: ActivityCategory;
    metadata?: ActivityLogMetadata;
}
/**
 * Activity log from sensors (browser, desktop, mobile)
 * Requirements: 7.2
 */
export interface ActivityLogEvent extends BaseEvent {
    eventType: 'ACTIVITY_LOG';
    payload: ActivityLogPayload;
}
/**
 * State change payload
 * Requirements: 7.3
 */
export interface StateChangePayload {
    previousState: string;
    newState: string;
    trigger: string;
    timestamp: number;
}
/**
 * State change event
 * Requirements: 7.3
 */
export interface StateChangeEvent extends BaseEvent {
    eventType: 'STATE_CHANGE';
    payload: StateChangePayload;
}
/**
 * User action payload
 * Requirements: 7.4
 */
export interface UserActionPayload {
    actionType: string;
    targetEntity: string;
    parameters: Record<string, unknown>;
    result: string;
}
/**
 * User action event
 * Requirements: 7.4
 */
export interface UserActionEvent extends BaseEvent {
    eventType: 'USER_ACTION';
    payload: UserActionPayload;
}
/**
 * Heartbeat payload
 * Requirements: 7.5
 */
export interface HeartbeatPayload {
    clientVersion: string;
    /** Platform: 'macos' | 'windows' | 'linux' | 'ios' | 'android' | 'chrome' */
    platform: string;
    connectionQuality: ConnectionQuality;
    /** Hash of local state for conflict detection */
    localStateHash: string;
    /** Capabilities: ['sensor:app', 'action:close_app', etc.] */
    capabilities: string[];
    /** Seconds since client start */
    uptime: number;
}
/**
 * Periodic heartbeat from clients
 * Requirements: 7.5
 */
export interface HeartbeatEvent extends BaseEvent {
    eventType: 'HEARTBEAT';
    payload: HeartbeatPayload;
}
/**
 * Domain breakdown entry for browser sessions
 */
export interface DomainBreakdownEntry {
    domain: string;
    /** Duration in seconds */
    duration: number;
    /** Active duration in seconds */
    activeDuration: number;
    category: ActivityCategory;
    visitCount: number;
}
/**
 * Enhanced browser activity payload
 * Requirements: 5.6-5.20
 */
export interface BrowserActivityPayload {
    url: string;
    title: string;
    domain: string;
    /** Unix timestamp (ms) */
    startTime: number;
    /** Unix timestamp (ms) */
    endTime: number;
    /** Total time on page (seconds) */
    duration: number;
    /** Time with user interaction (seconds) */
    activeDuration: number;
    /** Time without interaction (seconds) */
    idleTime: number;
    category: ActivityCategory;
    /** 0-100 */
    productivityScore: number;
    /** 0-100 percentage */
    scrollDepth: number;
    /** clicks, inputs, etc. */
    interactionCount: number;
    isMediaPlaying: boolean;
    /** seconds */
    mediaPlayDuration: number;
    referrer?: string;
    navigationType: NavigationType;
    searchQuery?: string;
    searchEngine?: SearchEngine;
}
/**
 * Enhanced browser activity log with detailed tracking
 * Requirements: 5.6-5.20
 */
export interface BrowserActivityEvent extends BaseEvent {
    eventType: 'BROWSER_ACTIVITY';
    payload: BrowserActivityPayload;
}
/**
 * Browser session payload
 * Requirements: 5.13-5.17
 */
export interface BrowserSessionPayload {
    sessionId: string;
    startTime: number;
    endTime: number;
    /** seconds */
    totalDuration: number;
    /** seconds with browser focused */
    activeDuration: number;
    domainBreakdown: DomainBreakdownEntry[];
    tabSwitchCount: number;
    /** switches within 3 seconds */
    rapidTabSwitches: number;
    uniqueDomainsVisited: number;
    productiveTime: number;
    distractingTime: number;
    neutralTime: number;
    /** 0-100 */
    productivityScore: number;
}
/**
 * Browser session summary event
 * Requirements: 5.13-5.17
 */
export interface BrowserSessionEvent extends BaseEvent {
    eventType: 'BROWSER_SESSION';
    payload: BrowserSessionPayload;
}
/**
 * Tab switch payload
 * Requirements: 5.3, 5.17
 */
export interface TabSwitchPayload {
    fromTabId: number;
    toTabId: number;
    fromUrl: string;
    toUrl: string;
    fromDomain: string;
    toDomain: string;
    /** milliseconds */
    timeSinceLastSwitch: number;
    /** < 3 seconds since last switch */
    isRapidSwitch: boolean;
}
/**
 * Tab switch event for distraction detection
 * Requirements: 5.3, 5.17
 */
export interface TabSwitchEvent extends BaseEvent {
    eventType: 'TAB_SWITCH';
    payload: TabSwitchPayload;
}
/**
 * Browser focus payload
 * Requirements: 5.9, 5.16
 */
export interface BrowserFocusPayload {
    /** true = browser gained focus, false = lost focus */
    isFocused: boolean;
    previousState: BrowserFocusState;
    /** seconds (only when losing focus) */
    focusDuration?: number;
}
/**
 * Browser focus event
 * Requirements: 5.9, 5.16
 */
export interface BrowserFocusEvent extends BaseEvent {
    eventType: 'BROWSER_FOCUS';
    payload: BrowserFocusPayload;
}
/**
 * Entertainment mode event payload
 * Requirements: 8.6, 10.3, 12.1, 12.2
 */
export interface EntertainmentModePayload {
    action: 'start' | 'stop';
    sessionId: string;
    timestamp: number;
    quotaUsedBefore: number;
    quotaUsedAfter?: number;
    duration?: number;
    sitesVisited?: string[];
    reason?: EntertainmentStopReason;
}
/**
 * Entertainment mode event
 * Requirements: 8.6, 10.3, 12.1, 12.2
 */
export interface EntertainmentModeEvent extends BaseEvent {
    eventType: 'ENTERTAINMENT_MODE';
    payload: EntertainmentModePayload;
}
/**
 * Work start event payload
 * Requirements: 14.1, 14.2, 14.9, 14.10
 */
export interface WorkStartPayload {
    date: string;
    configuredStartTime: string;
    actualStartTime: number;
    delayMinutes: number;
    trigger: 'first_pomodoro' | 'airlock_complete';
}
/**
 * Work start event
 * Requirements: 14.1, 14.2, 14.9, 14.10
 */
export interface WorkStartEvent extends BaseEvent {
    eventType: 'WORK_START';
    payload: WorkStartPayload;
}
/**
 * Union type for all event types
 */
export type OctopusEvent = ActivityLogEvent | StateChangeEvent | UserActionEvent | HeartbeatEvent | BrowserActivityEvent | BrowserSessionEvent | TabSwitchEvent | BrowserFocusEvent | EntertainmentModeEvent | WorkStartEvent | ChatMessageEvent | ChatActionEvent | ChatHistoryRequestEvent;
//# sourceMappingURL=events.d.ts.map