#!/usr/bin/env bash
# env-manager.sh — Feature environment lifecycle management
# Usage:
#   scripts/env-manager.sh create <name>   # Create DB + .env file
#   scripts/env-manager.sh start <name>    # Start feature dev server
#   scripts/env-manager.sh stop <name>     # Stop feature dev server
#   scripts/env-manager.sh destroy <name>  # Delete DB + .env file
#   scripts/env-manager.sh list            # List all active feature environments

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENVS_DIR="$PROJECT_DIR/.envs"
PID_DIR="$ENVS_DIR/.pids"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${GREEN}[env-manager]${NC} $*"; }
warn() { echo -e "${YELLOW}[env-manager]${NC} $*"; }
err() { echo -e "${RED}[env-manager]${NC} $*" >&2; }
info() { echo -e "${CYAN}[env-manager]${NC} $*"; }

# Compute port from feature name: 3101 + (hash % 99)
compute_port() {
  local name="$1"
  local hash
  hash=$(echo -n "$name" | cksum | cut -d' ' -f1)
  local offset=$((hash % 99))
  local port=$((3101 + offset))

  # Check for port conflicts with other feature envs, increment if needed
  while is_port_taken "$port" "$name"; do
    port=$((port + 1))
    if [ "$port" -ge 3200 ]; then
      port=3101
    fi
  done

  echo "$port"
}

# Check if a port is already assigned to a different feature env
is_port_taken() {
  local port="$1"
  local current_name="$2"
  if [ -d "$ENVS_DIR" ]; then
    for env_file in "$ENVS_DIR"/.env.feat-*; do
      [ -f "$env_file" ] || continue
      local other_name
      other_name=$(basename "$env_file" | sed 's/.env.feat-//')
      if [ "$other_name" != "$current_name" ]; then
        if grep -q "PORT=$port" "$env_file" 2>/dev/null; then
          return 0
        fi
      fi
    done
  fi
  return 1
}

cmd_create() {
  local name="${1:?Usage: env-manager.sh create <name>}"
  local db_name="vibeflow_feat_${name}"
  local env_file="$ENVS_DIR/.env.feat-${name}"

  mkdir -p "$ENVS_DIR" "$PID_DIR"

  if [ -f "$env_file" ]; then
    warn "Feature environment '$name' already exists at $env_file"
    return 0
  fi

  local port
  port=$(compute_port "$name")
  local db_user="${USER:-$(whoami)}"
  local db_url="postgresql://${db_user}@localhost:5432/${db_name}?schema=public"

  # Create database
  log "Creating feature environment '$name'..."
  bash "$SCRIPT_DIR/ensure-db.sh" "$db_name"

  # Generate .env file
  cat > "$env_file" <<EOF
# Feature environment: $name
# Generated by env-manager.sh — do not commit
DATABASE_URL="$db_url"
PORT=$port
NEXTAUTH_URL="http://localhost:$port"
NEXTAUTH_SECRET="feat-${name}-secret-not-for-production"
DEV_MODE="true"
NEXT_PUBLIC_DEV_MODE="true"
EOF

  log "Feature environment '$name' created:"
  info "  Database: $db_name"
  info "  Port:     $port"
  info "  Env file: $env_file"
  info "  Start:    npm run dev:feat -- $name"
}

cmd_start() {
  local name="${1:?Usage: env-manager.sh start <name>}"
  local env_file="$ENVS_DIR/.env.feat-${name}"
  local pid_file="$PID_DIR/feat-${name}.pid"

  if [ ! -f "$env_file" ]; then
    warn "Environment '$name' not found. Creating it first..."
    cmd_create "$name"
    env_file="$ENVS_DIR/.env.feat-${name}"
  fi

  # Check if already running
  if [ -f "$pid_file" ] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
    local port
    port=$(grep '^PORT=' "$env_file" | cut -d= -f2)
    warn "Feature server '$name' is already running (PID: $(cat "$pid_file"), port: $port)"
    return 0
  fi

  local port
  port=$(grep '^PORT=' "$env_file" | cut -d= -f2)

  # Check if port is in use by another process
  if lsof -i ":$port" -sTCP:LISTEN &>/dev/null; then
    err "Port $port is already in use. Kill the process first or recreate the environment."
    return 1
  fi

  log "Starting feature server '$name' on port $port..."
  cd "$PROJECT_DIR"
  dotenv -e "$env_file" -- tsx watch --clear-screen=false server.ts &
  local pid=$!
  echo "$pid" > "$pid_file"

  log "Feature server '$name' started (PID: $pid)"
  info "  URL: http://localhost:$port"
}

cmd_stop() {
  local name="${1:?Usage: env-manager.sh stop <name>}"
  local pid_file="$PID_DIR/feat-${name}.pid"

  if [ ! -f "$pid_file" ]; then
    warn "No PID file found for '$name' — server may not be running"
    return 0
  fi

  local pid
  pid=$(cat "$pid_file")
  if kill -0 "$pid" 2>/dev/null; then
    log "Stopping feature server '$name' (PID: $pid)..."
    kill "$pid" 2>/dev/null || true
    # Wait briefly for graceful shutdown
    for i in {1..10}; do
      if ! kill -0 "$pid" 2>/dev/null; then
        break
      fi
      sleep 0.5
    done
    # Force kill if still running
    if kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null || true
    fi
    log "Feature server '$name' stopped"
  else
    warn "Process $pid is not running"
  fi

  rm -f "$pid_file"
}

cmd_destroy() {
  local name="${1:?Usage: env-manager.sh destroy <name>}"
  local db_name="vibeflow_feat_${name}"
  local env_file="$ENVS_DIR/.env.feat-${name}"

  # Stop server if running
  cmd_stop "$name" 2>/dev/null || true

  # Drop database
  if psql -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$db_name"; then
    log "Dropping database '$db_name'..."
    dropdb "$db_name" 2>/dev/null || {
      err "Failed to drop database '$db_name' (may have active connections)"
      err "Try: dropdb --force $db_name"
    }
  else
    warn "Database '$db_name' does not exist"
  fi

  # Remove env file
  if [ -f "$env_file" ]; then
    rm -f "$env_file"
    log "Removed $env_file"
  fi

  log "Feature environment '$name' destroyed"
}

cmd_list() {
  mkdir -p "$ENVS_DIR" "$PID_DIR"

  local found=0
  echo ""
  printf "${CYAN}%-20s %-8s %-25s %-10s${NC}\n" "NAME" "PORT" "DATABASE" "STATUS"
  printf "%-20s %-8s %-25s %-10s\n" "----" "----" "--------" "------"

  for env_file in "$ENVS_DIR"/.env.feat-*; do
    [ -f "$env_file" ] || continue
    found=1

    local name
    name=$(basename "$env_file" | sed 's/.env.feat-//')
    local port
    port=$(grep '^PORT=' "$env_file" | cut -d= -f2)
    local db_name="vibeflow_feat_${name}"

    local status="stopped"
    local pid_file="$PID_DIR/feat-${name}.pid"
    if [ -f "$pid_file" ] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
      status="${GREEN}running${NC}"
    fi

    printf "%-20s %-8s %-25s %-10b\n" "$name" "$port" "$db_name" "$status"
  done

  if [ "$found" -eq 0 ]; then
    echo "  (no feature environments found)"
    echo ""
    echo "  Create one with: npm run env:create -- <name>"
  fi
  echo ""
}

# Main dispatch
case "${1:-help}" in
  create)  shift; cmd_create "$@" ;;
  start)   shift; cmd_start "$@" ;;
  stop)    shift; cmd_stop "$@" ;;
  destroy) shift; cmd_destroy "$@" ;;
  list)    cmd_list ;;
  *)
    echo "Usage: env-manager.sh <command> [args]"
    echo ""
    echo "Commands:"
    echo "  create  <name>   Create feature DB + .env file"
    echo "  start   <name>   Start feature dev server"
    echo "  stop    <name>   Stop feature dev server"
    echo "  destroy <name>   Remove feature DB + .env file"
    echo "  list             List all feature environments"
    ;;
esac
