/**
 * Octopus Architecture - Action Types
 *
 * User action types for iOS -> Vibe Brain communication
 * and action result types for Vibe Brain -> iOS responses.
 *
 * NOTE: This file defines the "mobile" variants of UserActionPayload and
 * UserActionEvent (with optimisticId + data). The "server/legacy" variants
 * (with actionType/targetEntity/parameters/result) live in events.ts.
 * To avoid naming conflicts, the mobile variants are prefixed with "Mobile".
 */

import type { UserActionType, CommandPriority, ClientType } from './enums';

// UserActionType is defined in enums.ts and re-exported from there

// =============================================================================
// USER ACTION TYPES (iOS -> Vibe Brain)
// =============================================================================

/**
 * User action payload (iOS/mobile version with optimisticId + data)
 */
export interface MobileUserActionPayload {
  actionType: UserActionType;
  optimisticId: string;
  data: Record<string, unknown>;
}

/**
 * User action event (iOS/mobile -> Vibe Brain)
 */
export interface MobileUserActionEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: 'USER_ACTION';
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
  payload: MobileUserActionPayload;
}

// =============================================================================
// ACTION RESULT TYPES (Vibe Brain -> iOS)
// =============================================================================

/**
 * Action result payload
 */
export interface ActionResultPayload {
  optimisticId: string;
  success: boolean;
  error?: { code: string; message: string };
  data?: Record<string, unknown>;
}

/**
 * Action result command (Vibe Brain -> iOS)
 */
export interface ActionResultCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: 'ACTION_RESULT';
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
  payload: ActionResultPayload;
}
