/**
 * Octopus Architecture - Chat Types
 *
 * AI Chat event and command types for communication between
 * clients and the Vibe Brain.
 */

import type { ClientType, CommandPriority } from './enums';

// =============================================================================
// CHAT ATTACHMENT TYPES
// =============================================================================

export interface ChatAttachment {
  type: 'task' | 'project' | 'goal' | 'pomodoro';
  id: string;
  title: string;
}

// =============================================================================
// CHAT EVENT TYPES (Client -> Vibe Brain)
// =============================================================================

export interface ChatMessagePayload {
  conversationId: string;
  messageId: string;
  content: string;
  attachments?: ChatAttachment[];
}

export interface ChatMessageEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: 'CHAT_MESSAGE';
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
  payload: ChatMessagePayload;
}

export interface ChatActionPayload {
  conversationId: string;
  toolCallId: string;
  action: 'confirm' | 'cancel';
}

export interface ChatActionEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: 'CHAT_ACTION';
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
  payload: ChatActionPayload;
}

export interface ChatHistoryRequestEvent {
  /** UUID, generated by client */
  eventId: string;
  /** Event type discriminator */
  eventType: 'CHAT_HISTORY_REQUEST';
  /** User identifier */
  userId: string;
  /** Unique client instance ID */
  clientId: string;
  /** Client type identifier */
  clientType: ClientType;
  /** Unix timestamp (ms) */
  timestamp: number;
  /** Monotonic counter per client */
  sequenceNumber: number;
  payload: Record<string, never>;
}

// =============================================================================
// CHAT COMMAND TYPES (Vibe Brain -> Client)
// =============================================================================

export interface ChatResponsePayload {
  conversationId: string;
  messageId: string;
  type: 'delta' | 'complete';
  content: string;
  usage?: { inputTokens: number; outputTokens: number };
  /** True when message is an AI-initiated proactive push (S4) */
  isProactive?: boolean;
  /** Trigger that generated this proactive message (S4) */
  triggerId?: string;
}

export interface ChatResponseCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: 'CHAT_RESPONSE';
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
  payload: ChatResponsePayload;
}

export interface ChatToolCallPayload {
  conversationId: string;
  messageId: string;
  toolCallId: string;
  toolName: string;
  description: string;
  parameters: Record<string, unknown>;
  requiresConfirmation: boolean;
}

export interface ChatToolCallCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: 'CHAT_TOOL_CALL';
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
  payload: ChatToolCallPayload;
}

export interface ChatToolResultPayload {
  conversationId: string;
  messageId: string;
  toolCallId: string;
  success: boolean;
  summary: string;
}

export interface ChatToolResultCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: 'CHAT_TOOL_RESULT';
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
  payload: ChatToolResultPayload;
}

export interface ChatSyncPayload {
  conversationId: string;
  messages: Array<{
    id: string;
    role: string;
    content: string;
    metadata?: Record<string, unknown>;
    createdAt: string;
  }>;
}

export interface ChatSyncCommand {
  /** UUID */
  commandId: string;
  /** Command type discriminator */
  commandType: 'CHAT_SYNC';
  /** Target client type or 'all' for broadcast */
  targetClient: ClientType | 'all';
  priority: CommandPriority;
  /** Whether client must acknowledge */
  requiresAck: boolean;
  /** Unix timestamp, command expires after this */
  expiryTime?: number;
  /** Unix timestamp */
  createdAt: number;
  payload: ChatSyncPayload;
}
